### ISSUE TITLE
Download format tsv

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#100]
We currently have `SIMPLE_CSV` as a download format that returns a zipped tsv with a csv extension. This is understandably a source of confusion for our users and there are regularly issues related to it. @MattBlissett recently mentioned that we didn't change this as it was considered a part of the stable API v1. 

We have recently introduced other download formats (`species list`).

How about we introduce another download format: `SIMPLE_TSV` and use that instead when downloading through the interface. We could also include a readme in the zip describing how to open it in excel and how to cite and what url the download is available at, what datasets, ...?

**Comment by MattBlissett** [comment]
We can (and should) include a readme in all the download formats — we are usually fine to add something to the API, just not change or remove.

A simple spreadsheet format might be more useful, e.g. OpenDocument Spreadsheet. Although this has a limit of a million rows.

**Comment by MortenHofft** [comment]
A user who fell into "the csv trap", is suggesting the simple patch solution to at least write in the download mail that it is in fact a tsv. This seems like a good simple way to start fixing this.

**Comment by timrobertson100** [comment]
Seems reasonable. Please see top 2 of https://www.gbif.org/faq?q=csv as well

**Comment by MattBlissett** [comment]
> Download Information:
>     DOI: https://doi.org/10.21373/dl.owg3k3 (may take some hours before being active)
>     Creation Date: Friday, 2 August 2019 08:33:44 o'clock GMT
>     Records included: 0 records from 0 published datasets
>     Data size: 476 B
>     Download format: SIMPLE_CSV
>     Filter used:
>         CatalogNumber: cat1 or cat2 or cat3
> …
>    The SIMPLE_CSV ZIP file will be kept for six months…
> …
> For help with opening downloaded files, see
>     https://www.gbif-dev.org/faq?question=opening-gbif-csv-in-excel
> or the FAQ section of the GBIF website:
>     https://www.gbif-dev.org/faq

Propose changing to

>    Download format: simple tab-separated values (TSV)

>    The simple tab-separated values (TSV) file will be kept for six months…

**Comment by MortenHofft** [comment]
Adding a `SIMPLE_TSV` download options still seems like a presumably simple fix to me. The exact same as `SIMPLE_CSV` just with a `.tsv`

**Comment by MattBlissett** [comment]
The limitation is Microsoft Excel, or Windows generally.

Neither likes the `.tsv` extension (requiring "Show all files" or similar), but `.csv` is accepted.

Also, the Excel user interface refers to "Text/CSV" to include tab separated data.

**Comment by MortenHofft** [comment]
6 years later. Microsoft Excel opens tsv files just fine now (on mac). Trying to open a csv will still require the user to choose the correct delimiter. The import function still refers to CSV or text file.
