### ISSUE TITLE
Buffer ES search tiles

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#113]
The adhoc search maps need to add a buffer when querying ES.
I suspect at the moment they query ES clipped to the tile boundary, but we should add a 15-20% buffer all around (suggest make it a parameter)

This doesn't cause issue when doing a VT rendering in the browser but when the PNG server is rendering, it needs to be able to render circles that are centered off the tile. Without it, you get rendering like this:

![image](https://user-images.githubusercontent.com/237221/59664001-7b467f00-91b0-11e9-8198-4eda15dabda2.png)

Please pay attention to the dateline too - I don't know how ES will behave with queries spanning that.

**Comment by fmendezh** [comment]
We are already doing a buffer around the tile, [see](https://github.com/gbif/maps/blob/elasticsearch/vectortile-server/src/main/java/org/gbif/maps/resource/AddHocMapsResource.java#L67),  I will convert that in a parameter with that default value in that way we can play with different values

**Comment by fmendezh** [comment]
https://github.com/gbif/maps/commit/2fe0dde02430d4e95a404124dcd89e9ff5681e6a
I added a parameter with a default value of 0.125
