### ISSUE TITLE
Changes to a dataset network need to trigger reinterpretation.

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#122]
Adding/removing a dataset from a network needs to reinterpret all occurrences from that dataset, as we do for a license.

RegistryBasedOccurrenceMutator (although it doesn't know a network has recently been changed.)

**Comment by fmendezh** [comment]
This issue was fixed last week   https://github.com/gbif/occurrence/commit/ff5ed26a7c9638b380c7734e18708a3a342da6ae
