### ISSUE TITLE
Expose identifiedBy through search filter

### ISSUE THREAD

**Issue by kcopas** [gbif/occurrence#127]
It's only from poking around Bloodhound that I've recognized what I think is an imbalance in what we expose through the GBIF.org interface—we expose 'recordedBy' ([e.g.](https://www.gbif.org/occurrence/search?recorded_by=Tim%20Robertson&advanced=1)) to searching and filtering, but not 'identifiedBy'.

If we're on board with the concept of using a Bloodhound-style approach to credit and support recognition of individuals working with specimens, we should consider adding this to the filters available (like recordedBy, under the 'Advanced' set).

**Comment by muttcg** [comment]
API is ready:
https://www.gbif.org/occurrence/download/0010796-200613084148143
https://www.gbif.org/api/occurrence/search?advanced=true&locale=en&identified_by=Carmelino+S%C3%A1ntiz+Ru%C3%ADz

"total" : 237101310 with identifiedBy

**Comment by MattBlissett** [comment]
This was done at some point over the summer.

https://www.gbif.org/occurrence/search?identified_by=Carmelino%20S%C3%A1ntiz%20Ru%C3%ADz&advanced=1
