### ISSUE TITLE
ES network key search doesn't work

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#139]
https://www-es.gbif.org/occurrence/search?dataset_key=83a517aa-f762-11e1-a439-00145eb45e9a&advanced=1&network_key=2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6

The occurrences have a network key, but they are not returned in a search.

**Comment by asturcon** [comment]
I think I didn't take the network key into account because it doesn't appear in the parameters in the documentation(https://www.gbif.org/developer/occurrence). Anyway, since it works in the current API I will add it to the ES API.

**Comment by asturcon** [comment]
fixed in https://github.com/gbif/pipelines/commit/1cf2f61b14beb6ecf64253fec4bd3c21808dd9fd

It's deployed in DEV: http://api-es.gbif-dev.org/v1/occurrence/search?network_key=1f2c0cbe-40df-43f6-ba07-e76133e78c31
