### ISSUE TITLE
Last interpreted "before end of" search incorrect

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#140]
This should return all results, but I suspect it's choosing 1 October:

https://www-es.gbif.org/occurrence/search?last_interpreted=*,2019-10&advanced=1

Looks to be the same issue with eventDate etc.

The API documentation should also be updated to explain how year-only or month-only ranges behave. https://www.gbif.org/developer/summary#common

**Comment by asturcon** [comment]
fixed in https://github.com/gbif/occurrence/commit/68ede9f79bce2ac860013ae00d00e4af2d7f399d

Deployed in DEV

**Comment by asturcon** [comment]
deployed in PROD

**Comment by asturcon** [comment]
reopening since it's not handling months with 31 days correctly

**Comment by asturcon** [comment]
In PROD it's setting the upper bound to 2019-10-31T00:00:00.000Z

**Comment by asturcon** [comment]
The way of calculating the range was changed in occurrence project to use the java 8 time API and set the time to the maximum or minimum. This can be ported to gbif-api if we want to migrate it to java 8.
