### ISSUE TITLE
Pipelines/HDFS-backed downloads using incorrect queue

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#144]
The queue used is root.users.hdfs, but it needs to be changed to root.download-admin.

(The resource allocation in YARN requires this, otherwise downloads are very slow due to other work like maps and the HDFS table build.)

**Comment by fmendezh** [comment]
https://github.com/gbif/occurrence/commit/ceefee339ac21df246510047ac5ef80176cd239b
