### ISSUE TITLE
Get download by DOI

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/occurrence#149]
Could we please have an endpoint to get to a download by the DOI? Similar to http://api.gbif.org/v1/dataset/doi/ for datasets.

(method: https://github.com/gbif/occurrence/blob/master/occurrence-ws/src/main/java/org/gbif/occurrence/ws/resources/DownloadResource.java#L114)

**Comment by MattBlissett** [comment]
We already have one, but there was a bug which required the slash in the DOI to be URL escaped to `%2F`, and didn't support the `/datasets` request.

https://api.gbif-uat.org/v1/occurrence/download/10.15468/dl.np3b3h
https://api.gbif-uat.org/v1/occurrence/download/10.15468%2fdl.np3b3h
https://api.gbif-uat.org/v1/occurrence/download/10.15468%2Fdl.np3b3h
https://api.gbif-uat.org/v1/occurrence/download/10.15468/dl.np3b3h/datasets
https://api.gbif-uat.org/v1/occurrence/download/10.15468/dl.np3b3h/citation

**Comment by dnoesgaard** [comment]
I thought I had used it before, just forgot that it doesn't have a different endpoint, as is the case for datasets...
