### ISSUE TITLE
Enable search by coordinateUncertaintyInMeters

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#152]
Enable search by the DarwinCore term `coordinateUncertaintyInMeters` in the API.

This is already interpreted in pipelines, in Elasticsearch, in downloads but is not a searchable field in the API. This should be added enabling range queries similar to e.g. year functionality.

Requested by Darwin Core @tucotuco

**Comment by timrobertson100** [comment]
When available on dev environment, please comment on https://github.com/gbif/portal16/issues/1335 for the UI to be done

**Comment by tucotuco** [comment]
Thanks for adding this to the list!

**Comment by MattBlissett** [comment]
Closed by 771c3ecca10f2adc811892b8e026915ea092f04a 3 weeks ago, but I forgot to close the issue!

http://api.gbif.org/v1/occurrence/search?coordinateUncertaintyInMeters=0,100

http://api.gbif.org/v1/occurrence/search?coordinateUncertaintyInMeters=0,*

http://api.gbif.org/v1/occurrence/search?coordinateUncertaintyInMeters=100000,*

**Comment by tucotuco** [comment]
Awesome!
