### ISSUE TITLE
Automatic deletion of occurrence records no longer referenced by source of data

### ISSUE THREAD

**Issue by cgendreau** [gbif/occurrence#16]
The purpose of this issue is to capture the expected behavior for automatic deletion of occurrence records that are no longer referenced by their source of data.

- Get a list of datasets crawled after a certain dates (not implemented). Use the `modified` field since the crawler updates it to add a `machineTags`.
- Get the id of the last crawl: last crawl with `Finish status: NORMAL`
- Get facets of occurrences for this dataset by crawlId
e.g. http://api.gbif.org/v1/occurrence/search?datasetKey=9ea87732-b88e-488d-a02b-3dc6e9b885e0&facet=crawlId&limit=10
- Compare occurrence counts of latest crawl with previous crawls (if any)
  - if the previous crawls contains less than 33% of the last crawl, delete them automatically, otherwise send notification
  - if the previous crawl contains the double of the last crawl (± 5%) this may represent a change in the identifiers, send a notification
  - add comment in the registry if auto deletion is applied

**Comment by mdoering** [comment]
Alternatively, how about the crawl coordinator cleanup sends a new message CrawlCleanedUp with the dataset key and crawlid and we run a listener that follows your step 3&4?

Are you sure comparing to just the previous crawlid is good enough or would older records hang forever?

**Comment by timrobertson100** [comment]
The issue to consider with doing it immediately at the end of the crawl is that there is that the SOLR updates are not synchronous (i.e. rabbitmq decouples that) so you need to be sure SOLR has received all mutations.  One could verify that by inspecting the fragments emitted - e.g. if crawlID = X and N records were emitted, and SOLR reports N records for crawlID=X proceed.  But we need a periodic sweep anyway, so suggest implement that first and if we need something more reactive, add it later.

The original post means to review all records connected with previous crawlIDs, not just the immediately preceding one.

**Comment by timrobertson100** [comment]
Please see https://github.com/timrobertson100/overcrawl-console

**Comment by cgendreau** [comment]
After further testing and thinking it is not possible to use Solr.

All unchanged records will keep their original `crawlId` in Solr since the `FragmentProcessor` will set the status to `OccurrencePersistenceStatus.UNCHANGED` and the message will be ignored by the `VerbatimProcessor`. Since updating each unchanged record in Solr is not really a viable option this feature should use a Hive query to get the counts per `crawlId` for a dataset.

**Comment by mdoering** [comment]
to just know if autodeletion should kick in could you not just compare the total record count in solr with the fragments emitted?

**Comment by cgendreau** [comment]
yes Solr count should be use to check if we actually need to check for autodeletion. Previous comment edited.

**Comment by MattBlissett** [comment]
Christian implemented this ages ago, the console is now here: https://management-tools.gbif.org/overcrawls
