### ISSUE TITLE
Suspect that recordedByID and identifiedByID are swapped by accident

### ISSUE THREAD

**Issue by dshorthouse** [gbif/occurrence#170]
See

https://github.com/gbif/occurrence/blob/a8c81a8545f6752bdbbb7fb8e963f555c6b1bb2f/occurrence-hdfs-table/src/main/java/org/gbif/occurrence/download/hive/Terms.java#L272

vs

https://github.com/gbif/occurrence/blob/3685c53cd032e95cc1e8793161d0392527326fec/occurrence-download/src/main/java/org/gbif/occurrence/download/query/HiveQueryVisitor.java#L185

**Comment by dshorthouse** [comment]
Could also be somewhere in this comment https://github.com/gbif/occurrence/commit/1f83dece556eb334a4f7763d1975fe5e29279e2c#diff-4dec20605014b51955354ab7617e5485 where placement of recordedByID and identifiedByID in header of output got swapped relative to the rows of data.

**Comment by MattBlissett** [comment]
Very close!

The fault is that `verbatimTerms()`, which is used to generate the meta.xml and the TSV header line:

https://github.com/gbif/occurrence/blob/occurrence-0.125/occurrence-common/src/main/java/org/gbif/occurrence/common/TermUtils.java#L296

Has a different order to that in `GbifTerm`:

https://github.com/gbif/dwc-api/blob/dwc-api-1.27/src/main/java/org/gbif/dwc/terms/GbifTerm.java#L272-L273

and that ordering is used to generate the Hive query.

I will fix it quickly, then work on removing the two sources of lists of fields, which has caused a problem before.

**Comment by timrobertson100** [comment]
Thanks @MattBlissett 

There are now archives that are semi-corrupt in the wild up until the fix is deployed. These are newly added terms, so the impact will be low but it does leave us with two easy options for @dshorthouse 
  1. We patch fix the meta.xml and headers for all downloads affected, noting that these are really meant to be immutable files
  2. Bloodhound use a nasty hack along the lines of:

```
// fixup: gbif/occurrence #170
if (downloadDate <= fixDate) {
  ... swap values
}
 
```

More invasive changes could be to rewrite the files, offer them on a new URL, and e.g. alert all consumers on the web page.

@dshorthouse - as nasty as it is, I am inclined to suggest 2. is the better option to not change data others have received.

**Comment by dshorthouse** [comment]
@MattBlissett Thanks for this. Happy I haven't completely lost my mind. However, you did reinforce my hopelessness with Java code ;)~. When this ticket is closed, will that signal deployed to production?

@timrobertson100 Rather than adding carbonation, it'll be easier at my end to reopen the pipe and generate a new download serving good beer. I've made the assumption that specimen data are (mostly) mutable...and data providers need to see their fixes flow downstream as quickly as is financially possible...so I flush & rebuild, including the attributions that were made elsewhere than on Bloodhound because these too may once have contained errors. I have every expectation that data providers themselves will swap recordedByID and identifiedByID in error and then later fix their mapping. I call the attributor for identifiedByID or recordedByID in Bloodhound, "GBIF Sourced".

It is unlikely that this has affected anyone or any project other than the display on Bloodhound. The only possible issue I can think of is if orgs are making use of the Frictionless Data from Bloodhound to incorporate attributions back into their specimen data management systems. AFAIK, only two collections have done that to date & I believe it was merely to pull identifiers to supplement their own agents tables rather than to populate the more granular attributions.

**Comment by MattBlissett** [comment]
The change is deployed, so any download from 2020-05-29 13:00 UTC or later will have DWCA meta.xml, TSV header line and data that match up.

Thanks again for digging into this, David.

**Comment by dshorthouse** [comment]
Awesome! Thanks for the quick turnaround @MattBlissett. Now I have something to keep me busy this weekend.

**Comment by dshorthouse** [comment]
Oh oh. There might be some ghosts https://www.gbif.org/occurrence/download/0074091-200221144449610
