### ISSUE TITLE
broken namespace

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#174]
http://api.gbif.org/v1/occurrence/2251011249 has odd fields:
"http://unknown.org/rights": "Creative Commons - Share Alike",
"http://unknown.org/language": "en",
"http://unknown.org/rightsHolder": "Barcode of Life Datasystems"

**Comment by asturcon** [comment]
The dataset is using these fields in the wrong namespace:
- "http://rs.tdwg.org/dwc/terms/rights": "Creative Commons - Share Alike"
- "http://rs.tdwg.org/dwc/terms/language": "en"
- "http://rs.tdwg.org/dwc/terms/rightsHolder": "Barcode of Life Datasystems"

Those fields don't exist in that namespace: http://rs.tdwg.org/dwc/terms.htm

The verbatim values can be found here: http://api.gbif.org/v1/occurrence/2251011249/verbatim

@ahahn-gbif maybe we should contact the publisher so they can fix them

**Comment by ahahn-gbif** [comment]
https://www.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c is hosted (and generated) internally, running from https://hosted-datasets.gbif.org/ibol/ibol.zip, so this should be in our hands.

According to https://dwc.tdwg.org/terms/, this should be 
- http://purl.org/dc/terms/accessRights
- http://purl.org/dc/terms/language
- http://purl.org/dc/terms/rightsHolder

@thomasstjerne, would you be able to help fix?

**Comment by thomasstjerne** [comment]
I have triggered an ingestion for it now.
