### ISSUE TITLE
Data clustering misses things one day apart

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#177]
There are examples of data shared in two networks relating to the same observations but recorded a day apart.
This is raised by a user who set traps overnight, and used the day of setting the trap for one data set, but the collection date (next day) in iNaturalist.

We should define a rule that relates records falling into this scenario.

**Comment by MattBlissett** [comment]
How would we tell this apart from someone who set two traps on successive nights, and set the eventDate consistently?

**Comment by timrobertson100** [comment]
We couldn't.

However, because the clustering is asserting relationships between similar records, not duplicate records and giving reasons its not inaccurate to link them (similar location, recorder, recorded within a time threshold) and in some cases desirable. 

The clustering is also only linking things across different datasets.
