### ISSUE TITLE
occurrence/search fails with scientificName

### ISSUE THREAD

**Issue by johnbaums** [gbif/occurrence#178]
Occurrence search by `scientificName` seems to be broken, returning `target values must be absolute`.

Example: http://api.gbif.org/v1/occurrence/search?scientificName=Ursus%20americanus

The [corresponding search](http://api.gbif.org/v1/occurrence/search?taxonKey=2433407&limit=2) using `taxonKey` succeeds.

**Comment by fmendezh** [comment]
Fix in this commit and in this branch https://github.com/gbif/occurrence/tree/issue-178
https://github.com/gbif/occurrence/commit/3ee90257062017cb703f6020405d686d3c15c71e

**Comment by fmendezh** [comment]
@johnbaums thanks for reporting this issue, it should be fine now
