### ISSUE TITLE
HTML email templates

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/occurrence#190]
Att: @mike-podolskiy90 

Just a few general comments—and perhaps @MortenHofft would like to chip in as well?

- [x] Font-families should match what we use on GBIF.org (Roboto,'Helvetica Neue',Helvetica,Arial,sans-serif)
- [x] Style the paragraph containg the citation with "background-color: #E8E8E8; padding: 10" (to make it pop!)
- [x] Remove bold styling from Download Information list element keys (i.e. DOI, Creation date, etc.) 
- [x] Suggested color palette to use: 
- GBIF green: #509E2F
- Dark grey: #534B4A
- Light grey: #E8E8E8
(and of course, black and white)

**Comment by MattBlissett** [comment]
>     * Font-families should match what we use on GBIF.org (Roboto,'Helvetica Neue',Helvetica,Arial,sans-serif)

In an email, I think this can only be a suggestion.

**Comment by mike-podolskiy90** [comment]
@dnoesgaard Thank you for the comments.
I support options 3 and 4.
I don't like how option 2 displays in the template. I'd suggest to skip it.
I also don't see the need to use the same fonts as the portal

**Comment by kcopas** [comment]
Can see we need to get you the branding police talk on visual identity. Consistent typefaces make for consistent UX.

Also, dismissing point no.2 means you’re downplaying the DOI citation, which is likely the most important strategic alteration Daniel’s suggestion. 

We need to work both of these out, please. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattBlissett** [comment]
Please bear in mind the previous emails were plain-text only, and HTML is a bonus as Mikhail was working on multilingual support.

There's only limited support for custom fonts in emails (I see today's BID newsletter uses Helvetica...).  It's not worth time fiddling with it, since users won't see it anyway. I'd also be cautious moving away from any defaults, since the emails will also be sent in Chinese and Arabic.

After the download link itself, the DOI is probably the most important part of the whole email, so I do support emphasizing the citation.

**Comment by kcopas** [comment]
Thanks, Matt. I meant to flag your earlier point about fonts.

What I probably meant more is that we don’t need to add Futura or whatever it was into the mix when “sans-serif” is as good as it will sometimes get in recipients’ inboxes. Count on Arial or Helvetica at best. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattBlissett** [comment]
This is the current email.

![image](https://user-images.githubusercontent.com/583320/94052222-ebdb4300-fdd8-11ea-937d-33906f30d199.png)

**Comment by kcopas** [comment]
Thanks for that, again, Matt.

Most important thing there is the DOI. The visual hierarchy should support that. 

The next biggest is probably the Download details header. 

The salutation should not be the biggest: it should be a pleasant greeting, not a 24-point bold shout. Body text, punctuated. 

Field names do not need bold weight. That makes them more important than the details, which is not true. 

Sorry if this is on the verge of being a rant, but we don’t enter people’s inboxes that often—which is why it matters so much. Happy to discuss, or not 🥴

**Comment by mike-podolskiy90** [comment]
My view of the option 2
![Screenshot 2020-09-23 at 20 37 32](https://user-images.githubusercontent.com/24795387/94055070-bafd0d00-fddc-11ea-9bb6-22450a4ef1c9.png)

**Comment by mike-podolskiy90** [comment]
My suggestion on lowering headers

![Screenshot 2020-09-23 at 21 20 48](https://user-images.githubusercontent.com/24795387/94059521-d539e980-fde2-11ea-8654-f52ba2300257.png)

**Comment by mike-podolskiy90** [comment]
or even lower

![Screenshot 2020-09-23 at 21 32 39](https://user-images.githubusercontent.com/24795387/94060581-78d7c980-fde4-11ea-828e-4611209b5dbc.png)

**Comment by dnoesgaard** [comment]
This is a mock-up of my suggestions combined

<img width="600" alt="Screenshot 2020-09-24 at 08 26 52" src="https://user-images.githubusercontent.com/21358085/94108576-d9482480-fe3f-11ea-998d-f4f14e603f4f.png">

Also, note that the HMTL is quite bloated with lots of redundant styling, e.g. defining font families within every single header, paragraph and list element—something we should probably avoid in an email.

**Comment by kcopas** [comment]
In this, with all the extraneous bolding removed, I’d suggest going ahead and emboldening “please use the following citation”.

**Comment by dnoesgaard** [comment]
Like this?

<img width="619" alt="Screenshot 2020-09-24 at 08 44 33" src="https://user-images.githubusercontent.com/21358085/94110018-3513ad00-fe42-11ea-8c2f-521e47f3163b.png">

**Comment by dnoesgaard** [comment]
Or perhaps, even clearer?

<img width="606" alt="Screenshot 2020-09-24 at 08 49 30" src="https://user-images.githubusercontent.com/21358085/94110416-e6b2de00-fe42-11ea-882c-9068828b0813.png">

**Comment by kcopas** [comment]
Yes, better 2.

**Comment by dnoesgaard** [comment]
(h/t @timrobertson100 for that one)

**Comment by fmendezh** [comment]
I'd like to enforce a practical decision here, my suggestions:

1. We can use the newsletter as a reference, it doesn't use the Roboto font, which is the most problematic, in there I found: Helvetica, Arial, 'Helvetica Neue', Helvetica and sans-serif. In my opinion, Arial should be always in the [list](https://websitesetup.org/web-safe-fonts-html-css/). Maybe we can just copy the newsletter CSS section here, and use that with a couple of adjustments for font sizes in headers.
2. Change the color schema to be as closest as possible to the newsletter 
3. Font size: I am fine with almost whatever sizes as long the DOI is prominent

**Comment by mike-podolskiy90** [comment]
My final suggestion

![Screenshot 2020-09-24 at 09 34 12](https://user-images.githubusercontent.com/24795387/94114956-56c46280-fe49-11ea-8d41-8ebe950ee518.png)

**Comment by mike-podolskiy90** [comment]
@dnoesgaard HTML is bloated because we have to use inline styles otherwise we can't guarantee everything displays correctly. Keep in mind it's not just a regular internet page, it's a freemarker email template which will be displayed in the mail, not browser

**Comment by dnoesgaard** [comment]
Ok, I will let you worry about the HTML :)

But can we please not introduce new shades of green? A simple light grey (#E8E8E8) padding on the citation paragraph is sufficient for making it stand out.

**Comment by kcopas** [comment]
I think standard black/dark text on light grey bkgd would suffice—the three greens distracts, rather than emphasizing. Simpler would be better.

**Comment by MortenHofft** [comment]
I'm late to this issue. I think you have done a great job @mike-podolskiy90 🎉  - styling emails is awful and a discipline of its own. My only comment would be to increase the top margin on headlines (`citation`, `download information`, `download file retention`) - personally I prefer headlines to be closer to the paragraph below than the one above.
