### ISSUE TITLE
when does extensions show? And where?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#195]
There is something about the way we show extensions that is confusing or a bug.
I'm using https://www.gbif.org/occurrence/1949672490 as an example

**When does extensions show**
https://api.gbif.org/v1/occurrence/1949672490/fragment has an extension (Amplification)
https://api.gbif.org/v1/occurrence/1949672490/verbatim has `"extensions": {}`
https://api.gbif.org/v1/occurrence/1949672490 also has `"extensions": {}`

**Nested or not**
And for the interpreted record https://api.gbif.org/v1/occurrence/1949672490 I see that we have
* `"extensions": {}`
* `facts: []`
* `relations: []`
* `identifiers: []`

When does an extension belong under the `extensions` object and when does it get its own top level field?

**Comment by muttcg** [comment]
Amplification worked only on DEV and was as a concept functional, but it didn't go to prod

**Comment by muttcg** [comment]
Measurement and fact example:
http://c6n1.gbif.org:9200/occurrence/_search?q=gbifId:1810011935 - has data
https://api.gbif.org/v1/occurrence/1810011935/fragment - has data
https://api.gbif.org/v1/occurrence/1810011935 - no data
https://www.gbif.org/occurrence/1810011935 - looks like data from the fragment

**Comment by MortenHofft** [comment]
> https://www.gbif.org/occurrence/1810011935 - looks like data from the fragment

Indeed it is from the fragment. That was changed to use fragment data 13 months ago in the portal because it was removed from verbatim https://github.com/gbif/portal16/commit/ab3b8fa755614869f730f70f59d14a2bdaa0e4c6

**Comment by MortenHofft** [comment]
> Amplification worked only on DEV and was as a concept functionality, but it didn't go to prod

I'm not sure I understand. Isn't the extension old. And didn't we use to include all extensions in the verbatim response?
https://tools.gbif.org/dwca-validator/extension.do?id=http://data.ggbn.org/schemas/ggbn/terms/Amplification

**Comment by muttcg** [comment]
> > Amplification worked only on DEV and was as a concept functionality, but it didn't go to prod
> 
> I'm not sure I understand. Isn't the extension old. And didn't we use to include all extensions in the verbatim response?
> https://tools.gbif.org/dwca-validator/extension.do?id=http://data.ggbn.org/schemas/ggbn/terms/Amplification

Sorry I was talking about interpretation, we have a prototype for that, but of course, all must be in verbatim record

**Comment by MortenHofft** [comment]
Related to https://github.com/gbif/portal-feedback/issues/1760

**Comment by marcos-lg** [comment]
The fix to show the extensions in the occurrence endpoints is in DEV.

**Comment by marcos-lg** [comment]
Deployed in UAT

**Comment by MortenHofft** [comment]
A summary from a different media:

We have 3 views of occurrence

**Fragment**
this can contain anything, can be JSON or XML. 

**Verbatim**
this is powered by ES. /occurrence/123/verbatim and in ES you will only find extensions that are in the list in config. This list is also what powers the hasExtension. The list is in the pipelines config. Currently it looks like

```
extensionsAllowedForVerbatimSet:
  - http://rs.tdwg.org/dwc/terms/Occurrence
  - http://rs.tdwg.org/ac/terms/Multimedia
  - http://data.ggbn.org/schemas/ggbn/terms/Amplification
  - http://data.ggbn.org/schemas/ggbn/terms/Cloning
  - http://data.ggbn.org/schemas/ggbn/terms/GelImage
  - http://data.ggbn.org/schemas/ggbn/terms/Loan
  - http://data.ggbn.org/schemas/ggbn/terms/MaterialSample
  - http://data.ggbn.org/schemas/ggbn/terms/Permit
  - http://data.ggbn.org/schemas/ggbn/terms/Preparation
  - http://data.ggbn.org/schemas/ggbn/terms/Preservation
  - http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact
  - http://zooarchnet.org/dwc/terms/ChronometricAge
  - http://zooarchnet.org/dwc/terms/ChronometricDate
  - http://purl.org/germplasm/germplasmTerm#GermplasmAccession
  - http://purl.org/germplasm/germplasmTerm#MeasurementScore
  - http://purl.org/germplasm/germplasmTerm#MeasurementTrait
  - http://purl.org/germplasm/germplasmTerm#MeasurementTrial
  - http://rs.tdwg.org/dwc/terms/Identification
  - http://rs.gbif.org/terms/1.0/Identifier
  - http://rs.gbif.org/terms/1.0/Image
  - http://rs.tdwg.org/dwc/terms/MeasurementOrFact
  - http://rs.gbif.org/terms/1.0/Multimedia
  - http://rs.gbif.org/terms/1.0/Reference
  - http://rs.tdwg.org/dwc/terms/ResourceRelationship
```

**Interpreted**
this will remain as it always has been. We interpret multimedia (audubon core, simple images) and we also copy the verbatim values for those extensions listed in [the enum](http://api.gbif.org/v1/enumeration/basic/Extension).
