### ISSUE TITLE
downloads showing up as being deleted

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#20]
We have 8 statuses for a download.

```
# Status
enum.downloadstatus.PREPARING=Preparing
enum.downloadstatus.RUNNING=Running
enum.downloadstatus.SUCCEEDED=Succeeded
enum.downloadstatus.CANCELLED=Cancelled
enum.downloadstatus.KILLED=Killed
enum.downloadstatus.FAILED=Failed
enum.downloadstatus.SUSPENDED=Suspended
enum.downloadstatus.unavailable=Unavailable
```
If it is succesful (SUCCEEDED) I ask for 
```
options = {
    method: 'HEAD',
    ...
};
var req = http.request(options, function (r) {
    console.log(r.statusCode == 200);
    // status code is 500 - same as when it has been deleted
    // only happens when refreshing often - seconds after it will be fine.
});
```

Could it be that we set SUCCEEDED before the file is actually really available? Or could it be caching?

**Comment by timrobertson100** [comment]
The file is exposed through the NFS mount to Hadoop.  It _could be_ that HDFS accepts the file, the workflow completes (SUCCEEDED) but there is a delay before the file appears over the NFS mount.  If that were true, I am not sure there will be an easy solution to this.

**Comment by MortenHofft** [comment]
i doubt that it is an actual issue honestly. Most people probably wait for the mail or refresh less often than me - i probably only noticed because i was testing. but now it is logged in case we get an issue from a confused user that wonders why the download has been deleted 2 minutes after they created it

**Comment by MattBlissett** [comment]
We need to add a ninth status, DELETED, since some >80GB downloads have been deleted.

We will then know when to show deleted, and in all other cases the failure should be temporary.

**Comment by MortenHofft** [comment]
I've added a clause to not show a download as deleted if it is less that a day old. it isn't a pretty solution, but it solved the issue from a user perspective i should think (worst case is that the link doesn't work and we have bigger issues then).
