### ISSUE TITLE
Rename the GADM fields in Hive occurrence table

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#208]
The `occurrence` table currently has the following which is not intuitive, and inconsistent with the API:

```
level0gid, level0name, level1gid, level1name, level2gid, level2name, level3gid, level3name
```

I suggest these should all have a `gadm` prefix to avoid confusion and to be ready to bring in the additional gazetteers we plan to.

**Comment by MattBlissett** [comment]
This would be an easy change if it also affected the API, i.e. DWCA downloads:

```diff
   public String simpleName() {
-    return name();
+    return "gadm" + Character.toUpperCase(name().charAt(0)) + name().substring(1);
   }
```

but that seems disruptive for a minor, internal convenience.
