### ISSUE TITLE
gbifIDs for dataset 7b9a08ea-f762-11e1-a439-00145eb45e9a all evaporated

### ISSUE THREAD

**Issue by dshorthouse** [gbif/occurrence#216]
Although the datasetKey, occurrenceID, institutionCode, collectionCode, catalogNumber do not appear to have changed for https://www.gbif.org/dataset/7b9a08ea-f762-11e1-a439-00145eb45e9a, all its gbifIDs for the 50k+ records are now different than they were just a few short weeks ago. For example, this https://www.gbif.org/occurrence/2981274415 used to be https://www.gbif.org/occurrence/1098951886, which has now evaporated. What in the processing or publishing happened?

**Comment by timrobertson100** [comment]
Thanks @dshorthouse

Since you seemingly have them to hand, can you please paste the previous record detail? 

I can see from the [ingestion history](https://registry.gbif.org/dataset/7b9a08ea-f762-11e1-a439-00145eb45e9a/ingestion-history) that the dataset was not modified between attempt 135 and 186. I find the record with catalogue number `...21455` in attempt 186 but not in 135 which suggests they may be changing identifiers at source.

**Comment by dshorthouse** [comment]
Here's what was behind `gbifID`: 1098951886
`occurrenceID`: http://id.snsb.info/snsb/collection/21636/30414/21455
`institutionCode`: M
`collectionCode`: BSMvplantscoll
`catalogNumber`: M-0109229 / 30414 / 21455

**Comment by timrobertson100** [comment]
Thanks - and when did you download that please?

**Comment by dshorthouse** [comment]
Nov 20, 2020 https://www.gbif.org/occurrence/download/0117791-200613084148143

**Comment by dshorthouse** [comment]
...although am now second-guessing myself & may have done some re-mapping when a whole swath of records from this and another dataset did indeed change their catalogNumber earlier in November & I caught them at the Nov 20 download. However, I would have expected the gbifIDs to remain the same between Nov 20 and now.

**Comment by MattBlissett** [comment]
For crawl attempts from 120 (and probably before, but that's the earliest we have) up to and including 180, we have this XML:

```
                                <abcd:UnitGUID>http://id.snsb.info/snsb/collection/21455/30233/21274</abcd:UnitGUID>
                                <abcd:SourceInstitutionID>SNSB-M</abcd:SourceInstitutionID>
                                <abcd:SourceID>BSMvplantscoll</abcd:SourceID>
                                <abcd:UnitID>M-0109048 / 30233 / 21274</abcd:UnitID>
                                <abcd:DateLastEdited>2015-03-09T12:29:08.613000</abcd:DateLastEdited>
```

With attempt 186 on 13 November, we instead have this XML:

```
                                <abcd:UnitGUID>http://id.snsb.info/snsb/collection/21455/30233/21274</abcd:UnitGUID>
                                <abcd:SourceInstitutionID>M</abcd:SourceInstitutionID>
                                <abcd:SourceID>BSMvplantscoll</abcd:SourceID>
                                <abcd:UnitID>M-0109048 / 30233 / 21274</abcd:UnitID>
                                <abcd:DateLastEdited>2015-03-09T12:29:08</abcd:DateLastEdited>
```

Note the SourceInstitutionID was changed, and the DateLastEdited was rounded.

**Comment by dshorthouse** [comment]
Thanks @MattBlissett, that appears to correspond to the timeframe I had noticed a change in `gbifID` but does not explain what happened between Nov 20 and yesterday with what appears to be yet another change in `gbifID`.

**Comment by MattBlissett** [comment]
Quarterly snapshot, 2020-10-01:

1098951886  SNSB-M  BSMvplantscoll  http://id.snsb.info/snsb/collection/21636/30414/21455   M-0109229 / 30414 / 21455

David's download, 2020-11-20:

{"gbifID":1098951886,"v_occurrenceID":{"string":"http://id.snsb.info/snsb/collection/21636/30414/21455"},"v_institutionCode":{"string":"M"},"v_collectionCode":{"string":"BSMvplantscoll"},"v_catalogNumber":{"string":"M-0109229 / 30414 / 21455"}...

Current occurrence store:

2981274415  M       BSMvplantscoll  http://id.snsb.info/snsb/collection/21636/30414/21455  M-0109229 / 30414 / 21455

**Comment by dshorthouse** [comment]
That helps a lot @MattBlissett. Looks like the `gbifID` hadn't changed except post-November 20; must have been another dataset I had been messing with. That said, perhaps we need to enhance the logic in why a new gbifID is issued. We clearly have the same specimen record with a mere subtle, administrative change.

**Comment by timrobertson100** [comment]
This does look odd. I can understand some circumstances that might result in an ID change here, but @MattBlissett and I are not yet sure why that would happen after the 20th November.

Two things spring to mind that could cause this:
1. There is bug in this area where we're leaving some IDs hanging around and it's actually the second run that picks up a change
2. Around the 20th November, they used the catalogue number with multiple occurrenceIDs

> perhaps we need to enhance the logic in why a new gbifID is issued.

I think you are correct David. This was originally developed at a time when occurrenceID did not exist. We originally stored both a mapping of the triplet->gbifID and the occurrenceID->gbifID so that gbifIDs did not change as occurrenceIDs were added. The only reason to continue to store them is to allow people to change their triplets (e.g. a CC) or their occurrenceIDs (e.g. they changed a URL) and as long as only one changes, we maintain stability. I wonder if we're at a time where occurrenceID are stable enough that if present, we use that and that alone.

**Comment by dshorthouse** [comment]
@timrobertson100 You and your team will know best, but I suspect we'll have a mixed bag of `occurrenceID` usage in perpetuity & it'd be near impossible to rely on it as hoped. That said, it's a shame that handling of legacy, poorly populated `occurrenceID` is spilling too deeply into instances where `occurrenceID` appears to be populated and used as intended.

**Comment by timrobertson100** [comment]
I will test running this dataset through UAT or Dev using replaying the state we saw at crawl time from attempts 120, 135, 180, 186, and 188 to see if this is repeatable and report the results. It will be good to determine how this has happened and if it is repeatable, a bug, or a limitation (i.e. working as designed, but a nuisance nonetheless). 

The files are available [here](http://download.gbif.org/tim/) for the test.

Currently blocked by https://github.com/gbif/pipelines/issues/445

**Comment by dshorthouse** [comment]
Here's one more issue with occurrenceIDs that *could* be much more pervasive (and scary!) than I realized. https://github.com/gbif/portal-feedback/issues/3166

**Comment by timrobertson100** [comment]
I have now run attempts `120`, `135`, `180`, `186` and `188` through [UAT](https://registry.gbif-uat.org/dataset/c9e910b2-d1de-400c-ba65-ffa92785d70f/ingestion-history) but am no wiser. These went through without apparent issue, and the [record](https://www.gbif-uat.org/occurrence/2841331412) with `catalogNumber` of `M-0109229 / 30414 / 21455` maintained the same id. 

The only things I can think of:
1.  something from an earlier attempt than `120` remained in the lookup table. We can't repeat this as we only have archives dating back to attempt 120
2. we have some nuisance bug (wouldn't this appear more regularly?)
3. some bad configuration was deployed for a short period (no one is aware of that) 
4. the BioCASe protocol endpoint was used at some point, and provided different content to the archives

I'm stumped as to what more we can do on this issue.

**Comment by timrobertson100** [comment]
@muttcg notes that it is interesting that the `fragmenter` step is reporting that it emitted only 26k records on https://registry.gbif.org/dataset/7b9a08ea-f762-11e1-a439-00145eb45e9a/ingestion-history

**Comment by dshorthouse** [comment]
I suppose what's done is done & there's little action anyone can presently take on this issue. You can close this issue. However, it like https://github.com/gbif/portal-feedback/issues/3166 are all signals that there's much left to iron out as we get serious about extended specimens, digital objects, or annotations. Who creates the identifiers, what are their responsibilities, who makes links among entities, what are their motivations, who polices these links, and who is responsible for their repair are all a swirl of issues that will bubble-up.

**Comment by timrobertson100** [comment]
Thanks @dshorthouse, you're not wrong. It's a great deal better than the early days, but people still change identifiers more than one would anticipate.

I still worry that this dataset could flip around more in the future depending on changes made, so we'll explore better diagnostic tools to review and prune the historical values used

**Comment by timrobertson100** [comment]
Please see https://github.com/gbif/occurrence/issues/216
