### ISSUE TITLE
occurrence search limit disregarded without warning

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#22]
Same as https://github.com/gbif/registry/issues/13

https://api.gbif.org/v1/occurrence/search?limit=600&mediaType=stillImage&q=herbarium&basis_of_record=PRESERVED_SPECIMEN 

returns 300 results

**Comment by MortenHofft** [comment]
always been like that it seems: http://dev.gbif.org/issues/browse/PF-1805

Would be nice with an error that there is a cap on limit wouldn't it?

**Comment by MattBlissett** [comment]
It's documented and it would be inappropriate to change this behaviour https://www.gbif.org/developer/summary

> limit | Controls the number of results in the page. Using too high a value will be overwritten                                 with the default                                 maximum threshold, depending on the service. Sensible defaults are used so this may be                                 omitted
