### ISSUE TITLE
Enable linking to records using original ID

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#220]
This is desired by GBIF France and by VertNet in the API and on the webpage.

> From our occurrence page (ex: https://openobs.mnhn.fr/openobs-hub/occurrences/b88279d3-0950-4347-930f-b97ef2304b32), we would like to have links to:
> - the GBIF occurrence page: https://www.gbif.org/occurrence/2599165010
> - the GBIF species page: https://www.gbif.org/species/2888811
>  
> However, our portal only knows our own occurrence or species uuids, not the GBIF ones.
> Since our uuids (Occurrence ID or TaxRef species ID) are known by gbif.org, I'm able to forge the gbif.org URL, by calling the GBIF API first.
>  
> But to avoid this 2-steps mechanism and help integration with other portals, what do you think about implementing such "redirection" service on your side?
>  
> calling https://www.gbif.org/occurrence/{datasetKey}/{occurrenceID}
> ==> would redirect to the right occurrence page, using the OccurrenceID of the given dataset
>  
> calling https://www.gbif.org/species/{datasetKey}/{sourceID}
> ==> would redirect to the right species page, using external taxon uuid (sourceID) defined in the checklist (datasetKey)
> (datasetKey= checklist dataset ID, like https://www.gbif.org/dataset/0e61f8fe-7d25-4f81-ada7-d970bbb2c6d6)

**Comment by MortenHofft** [comment]
The website already supports it https://github.com/gbif/portal16/issues/1453#issuecomment-746171331

**Comment by fmendezh** [comment]
API now supports lookup by dataset key and occurrenceID, some examples:

1. Occurrence interpreted lookup by {datasetKey}/{occurrenceID}:
[https://api.gbif.org/v1/occurrence/0001480b-76ca-4f30-86bc-f4292481554b/651D49B2-FF77-7F3F-E053-2614A8C050DE](https://api.gbif.org/v1/occurrence/0001480b-76ca-4f30-86bc-f4292481554b/651D49B2-FF77-7F3F-E053-2614A8C050DE)

2. Occurrence fragment lookup by {datasetKey}/{occurrenceID}:
[https://api.gbif.org/v1/occurrence/0001480b-76ca-4f30-86bc-f4292481554b/651D49B2-FF77-7F3F-E053-2614A8C050DE/fragment](https://api.gbif.org/v1/occurrence/0001480b-76ca-4f30-86bc-f4292481554b/651D49B2-FF77-7F3F-E053-2614A8C050DE/fragment)

3. Occurrence verbatim lookup by {datasetKey}/{occurrenceID}:
[https://api.gbif.org/v1/occurrence/0001480b-76ca-4f30-86bc-f4292481554b/651D49B2-FF77-7F3F-E053-2614A8C050DE/verbatim](https://api.gbif.org/v1/occurrence/0001480b-76ca-4f30-86bc-f4292481554b/651D49B2-FF77-7F3F-E053-2614A8C050DE/verbatim)

**Comment by marcos-lg** [comment]
I'm closing this issue since it seems that it's already implemented. If there is something else to do regarding this please reopen.
