### ISSUE TITLE
Remove the usage of the Extension enum in the ES response parser

### ISSUE THREAD

**Issue by marcos-lg** [gbif/occurrence#221]
Pipelines already controls what extensions we process and those extensions are different than the ones we currently have in the [Extension](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/Extension.java) enum, which is being used in the occurrence API to parse the ES responses. 

We should stop using this enum and accept any extension that is present in the ES index.

**Comment by timrobertson100** [comment]
Suggest handle this together with https://github.com/gbif/occurrence/issues/222
