### ISSUE TITLE
Support all DwC-A Extensions in the download 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#222]
Currently, DwC-A users receive only a limited number of extensions.

Now that GBIF many extensions into the Elastic index, and allow people to search for records with data in an extension we should enable capability to download of those data.

A user should be able to select which extensions to include in the DwC-A download.

**Comment by MattBlissett** [comment]
The initial implementation is for verbatim extensions only.

Example: https://api.gbif-uat.org/v1/occurrence/download/0000379-221031180420232

```
unzip -l 0000379-221031180420232.zip
Archive:  0000379-221031180420232.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     5734  2022-12-21 14:00   occurrence.txt
     5098  2022-12-21 14:00   verbatim.txt
      219  2022-12-21 14:00   multimedia.txt
      381  2022-12-21 14:00   ggbn_materialsample.txt
      381  2022-12-21 14:00   germplasm_germplasmmeasurementscore.txt
      142  2022-12-21 14:00   gbif_reference.txt
      122  2022-12-21 14:00   ggbn_preparation.txt
      283  2022-12-21 14:00   ggbn_cloning.txt
      655  2022-12-21 14:00   germplasm_germplasmaccession.txt
      169  2022-12-21 14:00   dwc_resourcerelationship.txt
      616  2022-12-21 14:00   dwc_identification.txt
      638  2022-12-21 14:00   ggbn_amplification.txt
      181  2022-12-21 14:00   ggbn_gelimage.txt
     1389  2022-12-21 14:00   ac_audubon.txt
       90  2022-12-21 14:00   ggbn_preservation.txt
      256  2022-12-21 14:00   obis_extendedmeasurementorfact.txt
      156  2022-12-21 14:00   gbif_multimedia.txt
      213  2022-12-21 14:00   germplasm_germplasmmeasurementtrait.txt
      171  2022-12-21 14:00   gbif_image.txt
      498  2022-12-21 14:00   dwc_chronometricage.txt
       61  2022-12-21 14:00   gbif_identifier.txt
      119  2022-12-21 14:00   ggbn_loan.txt
      188  2022-12-21 14:00   dwc_measurementorfact.txt
       85  2022-12-21 14:00   ggbn_permit.txt
      180  2022-12-21 14:00   germplasm_germplasmmeasurementtrial.txt
      112  2022-12-21 14:00   rights.txt
      278  2022-12-21 14:00   citations.txt
     4902  2022-12-21 14:00   dataset/0f51112f-a122-4d55-a3e0-12267186d3b9.xml
     2973  2022-12-21 14:00   metadata.xml
    76644  2022-12-21 14:00   meta.xml
---------                     -------
   102934                     30 files
```

1. Should we organize the files in the Zip file into a `verbatim/` subdirectory, which would make it clearer and allow us to interpret some of these extensions in the future?
2. Should we apply the same to verbatim.txt, i.e. only include it if `http://rs.tdwg.org/dwc/terms/Occurrence` is in the `verbatimExtension` array (which the portal could have ticked by default), and possibly rename it to `verbatim/dwc_occurrence.txt`?

3. Including unsupported extensions in the download currently breaks, it gives a `201` if `http://eol.org/schema/reference/Reference` is included but then fails: https://api.gbif-uat.org/v1/occurrence/download/0000385-221031180420232 
4. Or it gives a 404  if `http://rs.gbif.org/terms/1.0/DNADerivedData` is included, in both cases it should be `400`.

**Comment by CecSve** [comment]
https://github.com/gbif/portal-feedback/issues/4135

**Comment by CecSve** [comment]
#gbif/portal-feedback/issues/4135

**Comment by MattBlissett** [comment]
Extension data can now be downloaded through the API — for the website see https://github.com/gbif/portal16/issues/1910

API documentation: https://techdocs.gbif.org/en/data-use/api-downloads#verbatimextensions

**Comment by MattBlissett** [comment]
Yes, that's correct. All supported extensions are present in this month's occurrence snapshot.
