### ISSUE TITLE
Broken download for Bionomia format

### ISSUE THREAD

**Issue by gbif-portal** [gbif/occurrence#224]
**Broken download for Bionomia format**

The download as seen on https://www.gbif.org/occurrence/download/0138833-200613084148143 is broken (tried twice). Suspect there is an issue with the Bionomia download format.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/3671c8a780e7aaf8b5bf4e377829e9bb:03a5520be43d3d31582953fe9a2946f10923050bcb1c4bdfcafe57e4656bcc90401d47da308b731e4d32114d7c6c8e707e2cd05f73c506ffec8a8b9546d1e20f6650848e9f6035e06448c416b025596f)
System: Chrome 87.0.4280 / Mac OS X 11.1.0
Referer: https://www.gbif.org/occurrence/download/0138837-200613084148143
Window size: width 1674 - height 932
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-17T13:58:07.740Z',mode:absolute,to:'2020-12-17T14:04:07.740Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-17T13:58:07.740Z',mode:absolute,to:'2020-12-17T14:04:07.740Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by marcos-lg** [comment]
@dshorthouse We were checking this issue and indeed it's related to the changes in that pull request.

We don't have a field `country` in the table that we use for downloads and that's causing the breakage. However, we have the `countryCode` field instead which is the interpreted country. We were wondering if it'd be ok for you to use the `countryCode`.

**Comment by dshorthouse** [comment]
@marcos-lg Aha! That makes a lot of sense. I'll send another pull request to revert to what we had before. A user of the API at my end requested this so I'll explain to them that using the interpreted `countryCode` is the better bet.

**Comment by dshorthouse** [comment]
Here's the new pull request: https://github.com/gbif/occurrence/pull/225

**Comment by marcos-lg** [comment]
Deployed to production.
