### ISSUE TITLE
Explore random sample search

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#239]
Originating from https://github.com/plantnet/gbif-dl/issues/6

The request here is to provide the ability to quickly get a random sample of results rather than a group of records co-located in the result set.

For Hive downloads this could be easily achieved but it becomes harder to think how this might happen for Elastic-based queries. Needs exploration.

**Comment by fmendezh** [comment]
Elastic allows to score results using a a random function to get a random sampling of documents:

```
{
  "query": {
    "function_score": {
        "query": {
            "bool" : {
                "must" : {
                    "term" : { "basisOfRecord" : "OBSERVATION" }
                }
            }
        },
        "random_score": {}
    }
  }
}
```

**Comment by faroit** [comment]
@fmendezh @timrobertson100 is there some news on this issue?

**Comment by timrobertson100** [comment]
I'm afraid there hasn't been anything done, no. It's not something I'm aware anyone else is asking for so never gets prioritized.

Is your need a small random sample in a search response, or do you need a random sample for download (with DOI etc). The former would likely be a simpler implementation with the addition of a `shuffle=true` or so.

**Comment by faroit** [comment]
yes, its the former. The use case it training small-scale ml models where we would query e.g. a balanced set of `k` occurences from different species. If the query could yield results in random order we wouldn't need to retrieve all occurances first and shuffle then, thus reducing the amount of server load.

**Comment by marcos-lg** [comment]
Deployed to PROD. The parameter is called `shuffle` and it has to contain a seed with a random string, e.g.: https://api.gbif.org/v1/occurrence/search?basisOfRecod=MATERIAL_SAMPLE&shuffle=abcdefgh

The seed is necessary to page thru the results.
