### ISSUE TITLE
Download request endpoint gives 404 rather than 403

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#241]
e.g. https://api.gbif.org/v1/occurrence/download/0218552-200613084148143 with authentication, when isn't my download, and/or with the DELETE method.

**Comment by MattBlissett** [comment]
https://github.com/gbif/occurrence/blob/e66c2831b36377faebd6a4492aa3fb50ef4e58a3/occurrence-ws/src/main/java/org/gbif/occurrence/download/service/DownloadSecurityUtil.java

This returns 405, and doesn't allow a user with admin rights to e.g. cancel someone's download.

**Comment by ahakanzn** [comment]
Admin only restriction is removed from the first endpoint(https://github.com/gbif/registry/issues/588)
Second problem is seems solved right now. Closing since this is out of date.
