### ISSUE TITLE
Redirect non-admin user downloads to monthly downloads where applicable

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#242]
Where the user's download request already exists as a monthly download (e.g. all occurrences, or all present occurrences) the download API should redirect them to the newest matching monthly download.

The usual response is the new download key.  The new response will be a download key for a download not owned by that user -- i.e. they can't change the erase date, can't delete the download, and it won't show up in their user profile in the portal.

All this already exists as logic within the portal.  By moving it to the backend, we can avoid cases where API users accidentally omit the `predicate`, thus creating an all-occurrence download, sometimes hundreds of them.

#184 can be implemented at the same time.

CC @sckott, although I don't think this will be a problem for R/Python users.

**Comment by sckott** [comment]
Sounds good. I don't think that should cause any problems, but I'd appreciate a heads up when it's implemented at  https://api.gbif-uat.org/v1 so I can test - I've not heard of anyone doing this type of request with R or Python, although you might know from user-agent strings in your logs

**Comment by MattBlissett** [comment]
Hi @sckott; this is now deployed on UAT.  The GBIF portal works fine, so I think it should be OK.

**Comment by sckott** [comment]
Sorry for delay, started leave just before this was done. Thanks for doing this
