### ISSUE TITLE
LIKE predicates and wildcards

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#245]
In the interest of having consistent results across hosted portal queries (which aim to support the same predicate queries as download) and downloads I looked at the predicates with type LIKE.

It seems we [simply append an `*` to the end of all *small download* queries](https://github.com/gbif/occurrence/blob/master/occurrence-download/src/main/java/org/gbif/occurrence/download/query/EsQueryVisitor.java#L265). 

The [API v1 documentation](https://www.gbif.org/developer/occurrence#predicates) reads:
`like	|  search for a pattern  |   "value":"PAPS5-560%"`
That gives the impression that `%` is used as a wildcard and can be inserted anywhere.

It looks like we might have a bug leading to: 
* `*` and `?` might work as wildcard queries on small downloads and not on large downloads.
* And the `%` might discard results for small downloads (as it isn't present)
* wildcards are always appended to the end
* wildcards can not be used elsewhere

My interest is really just knowing how to map `like` predicates to ES, to get the same results when downloading

**Comment by MattBlissett** [comment]
The EsQueryVisitor (and its test) shows using a `*` symbol as a wildcard, and a wildcard is always appended, but the HiveQueryVisitor (and its test) uses `%`, and doesn't add any wildcard characters itself.

The public documentation also uses `%`.

There are zero downloads using `*`, and 25 non-empty downloads using `%`, though these are all from the same user.

It's probably most useful if we leave the position of the wildcard characters to the user.  `LIKE aoue` would be the same as `EQUALS aoeu`, but `LIKE %aoeu`, `LIKE aoeu%` and `LIKE %aoeu%` are different.

This allows a predicate pattern of `Nathan %Roberts` to match `Nathan X Roberts` without matching `Nathan Robertson` or `Jonathan Roberts`.

**Comment by MortenHofft** [comment]
I would be happy with that solution for downloads. For the UI I can disallow `%` as a first character (for performance reasons).
