### ISSUE TITLE
AWS public datasets - storage size estimate

### ISSUE THREAD

**Issue by nickynicolson** [gbif/occurrence#249]
Please could the page at https://github.com/gbif/occurrence/blob/dev/aws-public-data.md be updated with an outline estimate of the storage size of the dataset

**Comment by timrobertson100** [comment]
Yes.

In the meantime, please know that the first month is [10.15468/dl.79tfrn](https://doi.org/10.15468/dl.79tfrn) which shows as 84GB of compressed parquet.

**Comment by MattBlissett** [comment]
Tim — the download we store in a Zip file is 84GB, but the unzipped size (i.e. what's actually on AWS/Azure) is 108GB.
