### ISSUE TITLE
AWS public datasets - creation of local mirror / rsync

### ISSUE THREAD

**Issue by nickynicolson** [gbif/occurrence#250]
I've been talking with our HPC cluster admins about mirroring these datasets so that they are available on our compute infrastructure (at the crop diversity trust, shared with NHM and RBGE). They have asked:

> I assume there will be command line tools (eg rsync) that let us copy the data out, ideally only grabbing what's changed and not everything every time?

Can the page be updated (or a separate one created) with an indication of how a compute cluster admin could efficiently create a local mirror of the monthly snapshot?

**Comment by timrobertson100** [comment]
Yes. I don't know how that would look like yet, but I notice the AWS public datasets also have an SNS endpoint, so I _presume_ there is a notification service that can trigger on changes

**Comment by MattBlissett** [comment]
The AWS CLI might work, it has a `sync` subcommand:

```
aws --region eu-central-1 s3 ls s3://gbif-open-data-eu-central-1/ --no-sign-request
```

There's also [Rclone](https://rclone.org/).  A configuration [like this](https://rclone.org/s3/#anonymous-access-to-public-buckets):

```
[anons3]
type = s3
provider = AWS
env_auth = false
access_key_id =
secret_access_key =
region = eu-central-1
endpoint =
location_constraint =
acl = private
server_side_encryption =
storage_class =
```

is then used like this

```
rclone ls anons3:gbif-open-data-eu-central-1
rclone sync -v anons3:gbif-open-data-eu-central-1 ./gbif/
```

The SNS endpoint can be used to receive notifications, e.g. pings to URLs.  We usually create monthly exports on the 1st of the month, but that's not guaranteed.

**Comment by MattBlissett** [comment]
Also note, the data uploaded to AWS/Azure is created using a new GBIF download format, `SIMPLE_PARQUET`.  It's not yet documented, since it still needs some tuning when huge datasets are produced using it, but a download request like this: https://api.gbif.org/v1/occurrence/download/0250288-200613084148143 can be done by anyone.  Assembling it does take several hours.

This could be useful if you'd prefer only to have plant data, for example.

**Comment by MattBlissett** [comment]
Now documented at https://github.com/gbif/occurrence/blob/master/aws-public-data.md#downloadingmirroring-the-data
