### ISSUE TITLE
Download distinct species and datasets

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#26]
In the interface we have a tab for species in occurrence search. It is using facets to generate a sort of ad hoc checklist for a arbitrary query. Similar we can get the list of distinct datasets in that query. But the user have no way to download it. It seems a natural addition to download. A checkbox to include checklist or datasets.

**Comment by mdoering** [comment]
This would be really nice. It has been requested many times over the years, see also http://dev.gbif.org/issues/browse/POR-242

**Comment by aalbatross** [comment]
Available in prod 
Big download example 
https://www.gbif.org/occurrence/download/0006329-190307172214381
small download example 
https://www.gbif.org/occurrence/download/0006337-190307172214381

download request body sample : 
{
  "creator":"user",
  "notification_addresses": ["user@acad.edu"],
  "send_notification":"true",
  "format": "SPECIES_LIST",
  "predicate":{
  "type": "equals",
  "key": "TAXON_KEY",
  "value": "2431548"
}
}
