### ISSUE TITLE
Very wide, complex multipolygons are very slow to process

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#268]
[This download](https://www.gbif.org/occurrence/download/0032493-210914110416597)'s Hive query took almost 12 hours to complete (183 days CPU), because the [complex polygon optimization](https://github.com/gbif/occurrence/blob/master/occurrence-download/src/test/java/org/gbif/occurrence/download/query/HiveQueryVisitorTest.java#L280-L286) didn't do anything useful.

The optimization assumes (as in the test cases) a multipolygon would be something like an island group, so GTE/LTE predicates added for the bounding box would exclude most data.

This multipolygon covers most of the world, so there was little benefit.  A disjunction of bounding box queries from the polygons within the multipolygon would be better, or maybe converting multipolygons in Within queries to a disjunction of polygons prior to the existing optimization.

**Comment by timrobertson100** [comment]
We might also explore if the [ESRI UDF](https://github.com/Esri/spatial-framework-for-hadoop/blob/master/hive/src/main/java/com/esri/hadoop/hive/ST_Contains.java) does optimizations natively too.
