### ISSUE TITLE
Missing datasetName in download

### ISSUE THREAD

**Issue by niconoe** [gbif/occurrence#270]
Hello,

I've recently encountered cases where a DwC-A download from the GBIF portal has an empty `datasetName` field.

Example: in the [following download](https://www.gbif.org/occurrence/download/0038178-210914110416597) record with gbifId=297835694 has an empty `datasetName` in `occurrences.txt`, while the [occurrence page](https://www.gbif.org/occurrence/2978356945) gives a proper dataset name (Pl@ntNet automatically identified occurrences).

In that case, it looks like it might be cause by the non-ascii "@" character in the datasetName, but I've encountered it with seemingly less exotic dataset names (for example for [this occurrence](https://www.gbif.org/occurrence/2436133134))

**Comment by niconoe** [comment]
Hello GBIF team, do you already know if this this an issue you plan to tackle in the next few weeks/months? 

Otherwise I'll work on my (data consumer) side to avoid the issue, for example by making API calls to retrieve the missing dataset names based on the `datasetKey`.

Thanks a lot!

**Comment by MattBlissett** [comment]
@fmendezh, there aren't any empty datasetName values in Hive, could this be an ES issue? It's a small download.

**Comment by ManonGros** [comment]
Could this issue be related: https://github.com/gbif/portal-feedback/issues/3814?

**Comment by marcos-lg** [comment]
Fixed in PROD.

**Comment by niconoe** [comment]
Unfortunately, the issue doesn't seem fully solved (I recently removed my workaround in [GBIF Alert](https://github.com/riparias/gbif-alert) and the issue came back.

[This download](https://www.gbif.org/occurrence/download/0005513-230828120925497) for example has 27141 blank dataset names.

**Comment by marcos-lg** [comment]
I took a look at this issue again and I realized that the `datasetName` field is the darwin core field (https://dwc.tdwg.org/terms/#dwc:datasetName), not the title of the dataset in our registry, which is the one that the occurrence page displays.
