### ISSUE TITLE
duplicated GBIF-IDs in download

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#28]
From mail

> The problem that I encountered is this:
There are a number of duplicated gbifID in occurrence.txt of GBIF annotated archive of [this dataset](https://www.gbif.org/dataset/7e380070-f762-11e1-a439-00145eb45e9a). For instance, some of the duplicated gbifID are:
“””
1056617990
1056617989
1056617988
1056617987
1056617986
1056617985
1056617984
1056617983
1056617982
1056617981
1056617980
...
“”"
I have not verify if all duplicated rows are identical. 

The user saw it in [this download](https://www.gbif.org/occurrence/download/0005965-171025204727650)

**Comment by data-biodiversity-aq** [comment]
Hey, thanks a lot for your help Morten. Greatly appreciated.

In addition to the above mentioned download, I also just encountered the same situation in [this download](http://www.gbif.org/occurrence/download/0006042-171025204727650). Some of the duplicated gbifIDs are:
```
1456481279
1456481278
1456481277
1456481276
1456481275
1456481274
1456481273
1456481272
1456481271
1456481270
```

Thanks a lot!

**Comment by damianooldoni** [comment]
Thanks @MattBlissett to show that the problem is common to csv downloads as well: so it has nothing to do with the assembling of the DwCA.

I just got same problem working on a big DwCA download (<https://doi.org/10.15468/dl.gv89eu>, all plants in Belgium with coordinates). 
On the download page I read that file should contain 6739935 occurrences. However, the file `occurrence.txt` in DwCA zip file cointains 8358887 lines.

Via a text editor I found some duplicates. I also transformed the text file to a SQLite database in order to handle it within R. I can confirm the presence of duplicates. For example, gbifID keys `869887833`, `869887851`, `869887857`, `869887858`, `869887866` are present twice. No triplets (three lines with same occurrence) seem to be present.

**Comment by timrobertson100** [comment]
The cause of this appears to be a bug in Hive and I will commit a workaround today.

#### Symptoms
Occasionally seeing duplicate lines in CSV and DwC-A files. Often seeing inaccurate counts against datasets. 

#### Workflow
To understand the cause of this:
- GBIF offer Zip files as exports
- Zip uses Deflate compression which is not splittable or combinable
- GBIF wrote [an extension](https://github.com/gbif/hadoop-compress) to deflate which allows us to write compressed data in parallel which is stored in a `.def2` file containing compressed content along with [a custom footer](https://github.com/gbif/hadoop-compress/blob/master/src/main/java/org/gbif/hadoop/compress/d2/D2Footer.java). 
- The footer allows deflated files to be combined into a Zip file by concatenating deflated content, stripping the footer, but using the footer content to calculate the CRC and footer necessary for the Zip.
- Notably though `def2` files *are not splittable*
- As Hive has evolved, it has brought in optimisations. One of those is that it will run a second pass when doing a [CTAS](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-CreateTableAsSelect(CTAS)) which sweeps together the output files to avoid many small data files. This uses the [CombinehiveInputFormat](https://github.com/apache/hive/blob/branch-1.1/ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveInputFormat.java). This seemingly is trying to merge small `def2` files and split large ones. The splits are presented to mapper tasks as "file X, offset Y". However, it is not possible to start reading from "offset Y" and the mapper reads the full file. This is the cause of duplicates in the occurrence CSV.
- Secondly, the citation file reads the output of the CSV to attribute the counts by dataset. This suffers the same effect as above, with the [CombinehiveInputFormat](https://github.com/apache/hive/blob/branch-1.1/ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveInputFormat.java).

`CombineHiveInputFormat` should detect that these are compressed text files and therefore not splittable. I don't believe it is doing that, and I believe is the underlying bug.

The workaround is to apply the following which reverts Hive to the earlier behaviour:
```
-- Force use of a non-combining input format. Def2 files are not splittable. 
SET hive.input.format=org.apache.hadoop.hive.ql.io.HiveInputFormat;

-- Disable optimisation steps to merge the query output which incorrectly uses a HiveCombineInputFormat (always, even when hive.input.format is set to not do so)
SET hive.merge.mapfiles=false;
SET hive.merge.mapredfiles=false;
```

**Comment by timrobertson100** [comment]
Deployed and tested on www.gbif-uat.org 
Need to cherry pick 3 commits for production (master is not suitable for deploying).

**Comment by timrobertson100** [comment]
Fix in production
