### ISSUE TITLE
Status code on failing map tiles - GET by predicatehash

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#281]
When requesting maps by an unknown `predicateHash` (could be because the tile server had been restarted/redployed), then the error is a Status Code 500 (Internal Server Error) and nothing more. In my mind 500 indicates that it is beyond my control as a consumer.

I'm wondering if perhaps 400 (Bad Request) is more appropriate. And then send along a message telling the consumer what is wrong. E.g. JSON 
```
{
  "errorType": "UKNOWN_PREDICATE_HASH", 
  "errorMessage": "The predicate hash is unknown, try registering your query again"
}
```

The error format isn't that important in this case, but in general having errors as JSON with an enum as well as a message would be useful. It gives us a chance to translate the error using the enum and have a fallback to the message.

And in this case it is a clearer way to inform me as a consumer what the issue is" It is worth the effort to register my predicate again"

**Comment by timrobertson100** [comment]
Now returns 400 (commited in dev branch of maps, running in dev environment). 
Message is in plain text, not JSON.
