### ISSUE TITLE
Change public cloud drops to use CC-BY-NC data

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#284]
This is not to be implemented, pending management group decision. Public commentary is welcome.

There have been calls from users to change the monthly cloud drops on AWS and MS to include all GBIF content. As available, they are of limited use. These requests have come from the researchers implementing the MS GEO grant on Phylogentic Diversity and has been raised on [this discourse](https://discourse.gbif.org/t/public-data-cloud-snapshots/2755).

If approved, we would provide full exports, change the license of the snapshots and update the documentation to describe how one could filter to only data using a specific license.

**Comment by timrobertson100** [comment]
We've only had messages of support for this, so we will apply it in April.

The AWS metadata can be edited by a PR [here](https://github.com/awslabs/open-data-registry/blob/main/datasets/gbif.yaml) and we have to inform Tom A and the Planetary Computer team at Azure when it happens (private email threa).

**Comment by PietrH** [comment]
I'm excited to see this happening, more than once the existence of a more complete cloud drop would have made my queries easier, and will save me making many thousands of API calls in the future. Another positive note is that it'll allow me to make ad hoc complex queries, but still retain a static source even with a DOI if needed later on.

**Comment by MattBlissett** [comment]
This was applied starting with the 1 April 2022 export.

See also https://www.gbif.org/occurrence-snapshots
