### ISSUE TITLE
Support distanceFromCentroidInMeters term

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#295]
There's soon to be a `gbif:distanceFromCentroidInMeters` in the pipelines index, which should be added to the API for filtering and downloads.

With the existing numeric filters, setting an open range excludes null values.  Since the usual use of this filter would be a query  like `distanceFromCentroidInMeters=500,*` and also including the null values, it would be useful if that became  distanceFromCentroidInMeters  ≥ 500 OR isNull(distanceFromCentroidInMeters) in both the REST and download predicate APIs.

**Comment by fmendezh** [comment]
@MattBlissett the geoDistance filter supports multiple unit km, m, etc. Would it make sense to support the same for this filter too?

**Comment by MattBlissett** [comment]
I don't think so, since `Meters` is in the name of the term. Similar to `coordinateUncertaintyInMeters`.

**Comment by jhnwllr** [comment]
So this filter `coordinateUncertaintyInMeters` will support any positive values like 0m,100m, 200m, the same way `coordinateUncertaintyInMeters` works now? 

Just to repeat what @MattBlissett has said, almost all users will be wanting all the occurrences that are a minimum distance away from any centroid. 

"Give me all occurrences but the ones close to the centroid".

**Comment by MattBlissett** [comment]
Completed, though awaiting implementation in the portal UI.
