### ISSUE TITLE
S3 parquet snapshot has less records than expected

### ISSUE THREAD

**Issue by PietrH** [gbif/occurrence#316]
From this documentation: https://github.com/gbif/occurrence/blob/master/aws-public-data.md

> From 2022-04-01, snapshots include all data (CC0, CC-BY, CC-BY-NC). Filter using the license column if you need to exclude CC-BY-NC data.

I expect the S3 snapshots to contain all data

However, this query on the website: 
https://www.gbif.org/occurrence/search?country=BE&taxon_key=1766123

Results in 78 records, mostly iNaturalist. 

However, when I recreate this on databricks with the september snapshot:

```r
library(dplyr)
library(sparklyr)
gbif_snapshot_path <- "s3://gbif-open-data-eu-central-1/occurrence/2023-09-01/occurrence.parquet"
occ <- spark_read_parquet(sc, path = gbif_snapshot_path, memory = FALSE)
filter(occ, taxonkey == 1766123, countrycode == "BE")
```

I only get one record, from the iNaturalist Research Grade dataset. 

----

Why? Is there another limit on the snapshots that I'm unaware of?

**Comment by timrobertson100** [comment]
Can you please run the query with a scientificName starting with `Amphipyra pyr..` instead of taxonkey and report back?
I am wondering if this relates to a use of taxonKey, and acceptedTaxonKey, synonyms, and subspecies.


(sorry, I don't have time to do this right now myself)

**Comment by PietrH** [comment]
I'm getting 55 back from the september snapshot:

```r

gbif_tally_sn <- occ_gbif %>% group_by(scientificname, countrycode) %>% count() %>% filter(countrycode == "BE")
collect(gbif_tally_sn) %>% filter(stringr::str_starts(scientificname, stringr::fixed("Amphipyra pyr")))
# A tibble: 1 × 3
  scientificname                       countrycode     n
  <chr>                                <chr>       <int>
1 Amphipyra pyramidea (Linnaeus, 1758) BE             55
```

Am I using the wrong key?

Is the taxonkey field from the snapshot different than the one from the website/api? I would still expect the same results from both.

**Comment by PietrH** [comment]
Thanks for looking into it. It makes sense even if I don't like the result.

I believe I could also match against the backbone and use that. That would probably be preferable to thousands and thousands of API requests. 

For now I think I can get away with just dropping all observations above species rank by rerunning on `specieskey` instead. At least I think that'll fix it.

**Comment by timrobertson100** [comment]
Thanks @PietrH 

I'll close this as the question is answered and we'll bear in mind that we should consider if more fields should be added.
