### ISSUE TITLE
publishingOrgKey facet doesn't work

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#317]
In passing I found this:

Works: https://api.gbif.org/v1/occurrence/search?facet=publishingOrg&limit=0&facetLimit=1000
Doesn't: https://api.gbif.org/v1/occurrence/search?facet= publishingOrgKey&limit=0&facetLimit=1000

[The docs](https://www.gbif.org/developer/occurrence#p_publishingOrg) suggest these should be the same

**Comment by marcos-lg** [comment]
`publishingOrgKey`is not a valid param. In the docs it's not present in the parameters but it's present in the example response and I think the confusion comes from there.
