### ISSUE TITLE
eventDate and dateIdentified Validation Issue

### ISSUE THREAD

**Issue by CaroleSinou** [gbif/occurrence#32]
When the eventDate or dateIndentified is an interval, the dates are recorded as invalid in the portal.

The Darwin Core definition of these two terms include description of standard for intervals, but these standards are flagged as invalid in the portal, and thus, not used:
https://terms.tdwg.org/wiki/dwc:eventDate
https://terms.tdwg.org/wiki/dwc:dateIdentified

Examples of occurrences with intervals recorded as invalid:
https://www.gbif.org/occurrence/1054616551
https://www.gbif.org/occurrence/1437755100

**Comment by MattBlissett** [comment]
Same issue as https://github.com/gbif/portal-feedback/issues/652

Work is progressing, it's part of a larger project to rewrite a significant part of the data ingestion processing.

**Comment by MattBlissett** [comment]
These dates are no longer flagged as invalid, see https://www.gbif-uat.org/occurrence/1054616551
https://www.gbif-uat.org/occurrence/1437755100 (it will be on gbif.org later).

Doing something better than taking the start of the range will come later.
