### ISSUE TITLE
event date filter vs download gives different results

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#338]
https://www.gbif-uat.org/occurrence/download/0000001-240116135327229
vs
https://api.gbif-uat.org/v1/occurrence/search?dataset_key=d6167827-973d-429a-a00c-8ea294d62d80&event_date=2022-01-01&occurrence_id=1018

I would expect those 2 queries to return the same number of results

**Comment by MortenHofft** [comment]
equals seem to behave differently
https://www.gbif-uat.org/occurrence/download/0000003-240116135327229

**Comment by MattBlissett** [comment]
Yes, the `IN` predicate in the download isn't correct.  The search API and the `EQUALS` predicate match, and have correct behaviour.
