### ISSUE TITLE
event_date with ranges gives corrupt year, month and day data in the occurrence csv download

### ISSUE THREAD

**Issue by bwakkie** [gbif/occurrence#344]
Hi,

Not sure where to report this but the downloaded occurrence.csv has inconsistent year, month and day fields when the event_date is a range:

```
 gbif_id                     event_date                      year       m     d
"4400878366"	"2023-08-13T00:00Z/2023-08-16T00:00Z"        "2023"	"8"	""
"3448877312"	"2018-05-19T00:00Z/2018-06-02T00:00Z"        "2018"	""	""
"3357313354"	"1923-06-25/1923-06-27"	"1923"	"6"	""
"4136528431"	"2019-08-25T14:04Z"                          "2019"	"8"	"25"
"3306183861"	"1930-01"                                    "1930"	"1"	""
"3306191008"	"2004"                                       "2004"	""	""


```

**Comment by ManonGros** [comment]
@bwakkie the data looks as expected to me. What makes you write that the year, month and day data are corrupt?
As a side note, the way we way we interpret dates is documented here: https://techdocs.gbif.org/en/data-processing/temporal-interpretation

**Comment by bwakkie** [comment]
@ManonGros  You are right. I see what is happening now. Only parts of the range that are the same on both ends are used in the year, month, day fields. Makes sense although we lose valuable data of the range. See https://github.com/gbif/occurrence/issues/345 for this.

**Comment by MattBlissett** [comment]
The data is not lost, it is present in the eventDate field.
