### ISSUE TITLE
Better handling of event_date in occurrence csv

### ISSUE THREAD

**Issue by bwakkie** [gbif/occurrence#345]
Can you split the event_date in better parts in the occurrence csv's year, month and day?

e.g.

event_date, event_date_till?

at least adding a year_till month_till and day_till to not lose the rage?

year, year_till
month, month_till
day, day_till
hour, hour_till
minute, minute_till
seconds, seconds_till

**Comment by ManonGros** [comment]
@bwakkie Isn't the information in the eventDate field enough?

Note that most of the fields in the GBIF downloads, including the the eventDate and year, month and day fields are defined in the Darwin Core Standard: https://dwc.tdwg.org/terms/. Perhaps it would make sense to suggest the addition of new fields in the framework of the Darwin Core community? https://github.com/tdwg/dwc/issues

**Comment by MattBlissett** [comment]
The year, month and day fields are filled in only if the whole range of the eventDate covers a single year, month and/or day.  This is working as intended, as specified by Darwin Core.

I don't see the benefit to additional fields, as the information is already present in eventDate.
