### ISSUE TITLE
Explore feasibility of allowing legacy search behaviour for eventDate field

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#346]
We have had a request to allow searching on eventDate using the previous behaviour, where date ranges were mapped to a single point in time (usually the earliest part of the range, but other interpretations were possible).

We need to see what's possible with the current search index and download system.

**Comment by MattBlissett** [comment]
This was implemented and is live on api.gbif.org.

**Comment by MortenHofft** [comment]
Is that then `eventDateGte` and `eventDateLte`? Should we add it to the tech docs?

**Comment by MattBlissett** [comment]
It's a conscious decision not to document a legacy API, which was only requested for a single user.
