### ISSUE TITLE
predicate search example

### ISSUE THREAD

**Issue by abubelinha** [gbif/occurrence#347]
Hi

I am trying to figure out how to use the predicate search available in the new api documentation:
https://techdocs.gbif.org/en/openapi/v1/occurrence#/Searching%20occurrences/predicateSearchOccurrence

I don't recall predicate searches from the old documentation (only predicate downloads).
So I guess it is a new feature. 

This is a POST request and the endpoint /occurrence/search/predicate
Documentation just says "Full search across all occurrences specified _**using predicates (as used for the download API)**_."

But I would need a bit more info.  
When I click "try it out" button, I don't see any text area for providing my predicate.
And it doesn't provide any examples of such a predicate (other than the above sentence referring to download API). 

So I have some doubts:
- Should this request be authenticated? Download API requests must be so. 
- There is a example predicate here:  
   https://techdocs.gbif.org/en/data-use/api-downloads  
  But that json data example does not _simply_ contain a `predicate`, but some more things (`creator`, `sendNotification`, `notificationAddresses` ...):    
  I suppose most of those extra contents apply only for downloads, but not for searches (searches do not generate notifications by email, no download links, no authentication ... so I guess a predicate search request should not include them, should it?). 
- I also suppose no `"format"`, since no file will be generated ... just a JSON response as in usual api searches.

Conclusion: I have not clear how to proceed. 
I tried to reuse the download predicate example with and without that information but it is not working as I expect. 
This is my Python code (adapted from @ManonGros [download script](https://github.com/ManonGros/Small-scripts-using-GBIF-API/blob/master/query_species_list/functions_query_from_species_list.py#L59)):

```Python
	data = {
	  "predicate": {
		"type": "and",
		"predicates": [
		  {
			"type": "equals",
			"key": "TAXON_KEY",
			"value": 2651523
		  },
		  {
			"type": "in",
			"key": "COUNTRY",
			"values": [ "CL", "AR" ]
		  }
		]
	  }
	}
	import requests, json
	headers = {'Content-Type': 'application/json'}
	r = requests.post( "https://api.gbif.org/v1/occurrence/search/predicate" ,
				 data=json.dumps(data),  headers=headers)
	j = json.loads(r.text)
	print(j.get("count"))
```
A [web occurrence search with those filters](https://www.gbif.org/occurrence/search?country=CL&country=AR&taxon_key=2651523) returns less than 2000 records.
But the script outputs 2958175874 as results count, so looks like api is returning back all GBIF occurrences.
What am I doing wrong?

Thanks
@abubelinha

**Comment by MattBlissett** [comment]
Thanks for reporting. I agree it doesn't work:

```
curl -Ss -H "Content-Type: application/json" -X POST -d '{"limit":0,"predicate":{"type":"and","predicates":[{"type":"equals","key":"TAXON_KEY","value":2651523},{"type":"in","key":"COUNTRY","values":["CL","AR"]}]}}' https://api.gbif-dev.org/v1/occurrence/search/predicate; echo
```

Log messages: 

```
DEBUG [2024-04-22 14:53:34,788+0000] [http-nio-8084-exec-4] org.gbif.occurrence.ws.resources.OccurrenceSearchResource: Executing query, predicate ConjunctionPredicate[predicates=[EqualsPredicate[key=TAXON_KEY, value='2651523', matchCase='null'], InPredicate[key=COUNTRY, values=[CL, AR], matchCase=null]]], limit 0, offset 0
DEBUG [2024-04-22 14:53:34,789+0000] [http-nio-8084-exec-4] org.gbif.occurrence.search.es.OccurrenceSearchEsImpl: ES request: SearchRequest{searchType=QUERY_THEN_FETCH, indices=[occurrence], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, expand_wildcards_hidden=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=null, allowPartialSearchResults=null, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={"from":0,"size":0,"_source":{"includes":[],"excludes":["all","notIssues","*.verbatim","*.suggest"]},"sort":[{"year":{"order":"desc"}},{"month":{"order":"asc"}},{"id":{"order":"asc"}}],"track_total_hits":2147483647}}
```

**Comment by abubelinha** [comment]
Thanks for answering @MattBlissett 

I wasn't sure whether my json dictionary was correctly constructed or not, so I'd appreciate if you can confirm that too.

**Comment by abubelinha** [comment]
Sorry @MattBlissett for asking again but I don't know how commits work. 
I see you "committed something" and there it says "Resolves https://github.com/gbif/occurrence/issues/347"

"Resolves" means it is already solved? 
I added a "limit" value (which I was not using above) and tested it again, but I still get the same result. 

Is something wrong with my predicate or there is still something pending to be solved?

Thanks!

**Comment by MattBlissett** [comment]
Hi,

I've changed the code which should solve the issue, but it's not yet running on api.gbif.org.  I can let you know when that's done — I intend to combine it with some other small changes.

The Python code is fine.  The `limit=0` parameter was because I was only looking at the total count, not the records.

**Comment by MattBlissett** [comment]
This is now working in production:

```
curl -Ss -H "Content-Type: application/json" -X POST -d '{"predicate":{"type":"and","predicates":[{"type":"equals","key":"TAXON_KEY","value":2651523},{"type":"in","key":"COUNTRY","values":["CL","AR"]}]}}' https://api.gbif.org/v1/occurrence/search/predicate
```

**Comment by abubelinha** [comment]
Thanks @MattBlissett !!
Thanks also for explaining the limit=0 usage.
I am also interested in looking at the total count and using a multi-facet search.
Can you provide a minimal example? 
i.e. facetting countryCode and scientificName while providing facetLimit=20 and facetOffset=0
(taking the above example, or any other you want)

I have not clear how to construct the json and also request multiple pages of multiple facets at once. 
Which of the two facets would limit and offset apply to? Both of them at the same time?
i.e. first api call would return countryCode facets 0 to 20 and also scientificName facets 0 to 20 ?

BTW my question about missing textarea for providing a search predicate in the api the technical documentation page still stands.
I can't see where to type my predicate when using the "try it out" button.

**Comment by abubelinha** [comment]
Take a look 
https://techdocs.gbif.org/en/openapi/v1/occurrence#/Searching%20occurrences/predicateSearchOccurrence

I am trying to put facets and see how the constructed query would look like.
But it doesn't work. 
The example documentation tries to construct a GET request, while this is documented to be a POST request.

I suppose that doc page is still under construction but I would so much like to see a facet example predicate if you find a moment to explain how to construct it.

**Comment by abubelinha** [comment]
OK, I think I got it by try-error. The syntax would be:

```
data={"limit":0, "facets": ["SCIENTIFIC_NAME","COUNTRY_CODE"], "facetLimit":20}
data["predicate"] = { ... } # as above
```

Now the problem I see here is:  how should I navigate paged facets?
When requesting "results" there is a "count" value is returned, so we can calculate how many pages of results there will be.

But I don't see a similar "facetCount": we can see how many occurrences there are for each facet value, but we cannot see how many different facet values there are 
We need to blindly navigate an unknown number of pages until "facets" contains an empty list.  Is that the way to go?
Thanks for your help!

**Comment by MortenHofft** [comment]
yes, that is the way to go. facetOffset until you hit the limit. and probably have a limit=0. And probably not using scientific name unless you want to lump homonyms into one bucket.

```json
{
  "facets": ["TAXON_KEY"],
  "limit": 0,
  "facetOffset": 1,
  "predicate": {
    "type": "and",
    "predicates": [
      {
        "type": "equals",
        "key": "TAXON_KEY",
        "value": 2651523
      },
      {
        "type": "in",
        "key": "COUNTRY",
        "values": [
          "CL",
          "AR"
        ]
      }
    ]
  }
}
```

**Comment by abubelinha** [comment]
Thanks @MortenHofft for pointing that about taxon names.

Actually I was thinking about using acceptedTaxonKey facets: would that reduce facet numbers and return names accepted in the backbone? (so one facet might be accounting occurrences provided under different names which all of them do finally match with the same accepted one -either being synonyms or higherrank matches-)

Using taxonKey facets would instead return ids of those backbone names best-matching those name originally used by data provider (but not necessarily accepted in current backbone taxonomy). So, many more facets would be returned.

Am I right?

**Comment by abubelinha** [comment]
And one last question.   I am mostly interested in this api because I want to use some "not" predicates (avoid certain datasets).
But I wonder how this api compares to the normal one in terms of performance. 

As long as the same parameters are used in a more common search which can be run in both apis, is there any difference in using `occurrence/search` or `occurrence/search/predicate` ?   Any reasons for preferring one or the other?

Thanks again!

**Comment by MortenHofft** [comment]
They both end up querying the same index in the same manner. I wouldn't expect a performance difference if the queries was the same (just using POST vs GET). POST aren't cached in the browser, but that probably won't matter in your case
