### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#35]
http://api.gbif.org/v1/occurrence/search?facetLimit=1000&facet=country

returns
```
HTTP ERROR 500
Problem accessing /occurrence/search. Reason:

    Server Error
Caused by:
java.lang.NullPointerException
Powered by Jetty://
```

limit=10 works fine
http://api.gbif.org/v1/occurrence/search?facetLimit=10&facet=country

**Comment by MortenHofft** [comment]
surprisingly it works if adding certain filters (but not any)
http://api.gbif.org/v1/occurrence/search?facetLimit=1000&facet=country&datasetKey=0645ccdb-e001-4ab0-9729-51f1755e007e

**Comment by fmendezh** [comment]
At this moment all the supplied urls in previous comment work correctly
