### ISSUE TITLE
GeoTime - range query for contained concepts

### ISSUE THREAD

**Issue by CecSve** [gbif/occurrence#352]
Would it be possible to change the result of the query to match the order of the concepts? For example; 

https://api.gbif-uat.org/v1/occurrence/search?geologicaltime=LowerPennsylvanian,Bashkirian 
and 
https://api.gbif-uat.org/v1/occurrence/search?geologicaltime=Bashkirian,LowerPennsylvanian 

gives the message `Bashkirian contains LowerPennsylvanian` and `LowerPennsylvanian contains Bashkirian`, however technically, it is only `LowerPennsylvanian` that contains `Bashkirian`. Could the message for https://api.gbif-uat.org/v1/occurrence/search?geologicaltime=Bashkirian,LowerPennsylvanian instead be something like: `Bashkirian is contained within LowerPennsylvanian`?

**Comment by CecSve** [comment]
Yes, that seems like a good solution!

**Comment by marcos-lg** [comment]
Deployed to UAT.
