### ISSUE TITLE
Downloads does not include creator

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#363]
https://registry-api.gbif.org/occurrence/download/0001553-171109162308116
returns a creator (if asked by admin user)

But https://api.gbif.org/v1/occurrence/download/0001553-171109162308116
does not. I'm fairly certain that is a change. Since UI code written years ago assume the creator field to be available

**Comment by MortenHofft** [comment]
Maybe this is really a varnish issue, that it caches the first request it sees?

**Comment by MattBlissett** [comment]
> Maybe this is really a varnish issue, that it caches the first request it sees?

Yes, and I think the portal is making unnecessary requests, though it's not worth fixing that now.

It should be fixed in Varnish now, please check.
