### ISSUE TITLE
Explore improvements to SOLR real time indexing

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#37]
I took a quick look at the code and if my understanding is correct we should be able to increase production (i.e. rabbitmq) SOLR indexing by 10x throughout.

I gather the following happens
1. The [solr-indexer-cloud](https://github.com/gbif/gbif-configuration/blob/master/cli/prod/config/processor-indexer-cloud.yaml) uses the default batch size when pulling messages off Rabbit (50 if I remember correctly)
2. For each message in the batch it then works out the mutation (create, update, delete) and issues it to SOLR as a single operation.  See e.g. the [update method](https://github.com/gbif/occurrence/blob/master/occurrence-search/src/main/java/org/gbif/occurrence/search/writer/SolrOccurrenceWriter.java#L125)
3. If any fail, the batch is N'ACK'ed to RabbitMQ and the whole process is retried

If we pull modify the code to pull e.g. 1000 messages from RabbitMQ and then build 3 collections of mutations for each operation, the batch methods (e.g. [client.add(Collection)](https://lucene.apache.org/solr/5_2_0/solr-solrj/org/apache/solr/client/solrj/SolrClient.html#add(java.util.Collection)) can be used.  This would reduce the SOLR calls from 1000 to 3 and tests show this will likely yeild 10x performance update.

At 100,000/s this would translate to a full rebuild in under 3hrs and would remove the need for the MR based builds.  Reindexing could run while crawling continues too.

**Comment by MattBlissett** [comment]
For the eBird reindex I started many (8 or so) indexer processers. Towards the end, we started seeing performance of HBase drop, so 3 hours might be a little optimistic.

**Comment by fmendezh** [comment]
I improved Solr indexing by  processing mini-batches a few months ago
