### ISSUE TITLE
'recordedby' suggest cannot handle spaces

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#39]
there are [5 occurrences](https://api.gbif.org/v1/occurrence/search?recordedBy=Morten+Høfft) with recordedBy=Morten Høfft and the results are [case invariant](https://api.gbif.org/v1/occurrence/search?recordedBy=morten+h%C3%B8fft)

But yet there is no suggestions for that name
https://api.gbif.org/v1/occurrence/search/recordedBy?limit=10&q=Morten+Høfft

Same story for `Thomas Stjernegaard Jeppesen` or `Thomas Stjernegaard Jeppese`

It seems that any name with a space will not work

**Comment by muttcg** [comment]
gbif/pipelines/issues/253

**Comment by MattBlissett** [comment]
Looks to have been fixed some time ago.
