### ISSUE TITLE
NULL values for entire rows in occurrence databases

### ISSUE THREAD

**Issue by ManonGros** [gbif/occurrence#41]
Hi,

When querying for the dataset 'cd6e21c8-9e8a-493a-8a76-fbf7862069e5', the output gives rows filled with NULL values (to be precise, only one row out of 16 shows non NULL values).

Jan noticed that the last field: **ext_multimedia** before each set of NULL rows contains the characters "[{".

Query I used:

FROM occurrence_hdfs 
SELECT *
WHERE datasetkey = 'cd6e21c8-9e8a-493a-8a76-fbf7862069e5';

Thanks!
Marie

**Comment by MattBlissett** [comment]
The ext_multimedia field contains JSON, with embedded newlines.

```
  [{
    "type": "StillImage",
    "format": "image/jpeg",
    "identifier": "http://www.kew.org/herbcatimg/957920.jpg",
    "references": "http://specimens.kew.org/herbarium/K000059040",
    "title": null,
    "description": null,
    "source": null,
    "audience": null,
    "created": null,
    "creator": null,
    "contributor": null,
    "publisher": null,
    "license": "http://creativecommons.org/licenses/by/4.0/",
    "rightsHolder": "Royal Botanic Gardens, Kew"
  }]
```

Hive uses text format by default for intermediate processing, which then causes extra rows.

Do
```
set hive.query.result.fileformat=SequenceFile;
```
Or use the "gear" in Hue to set the same, and the results are as expected.

Tim/Fede etc — Is there anywhere we can set this as the default?

**Comment by MattBlissett** [comment]
PS, if this is just testing/playing/experimenting, please use the C4 / UAT environment.

**Comment by fmendezh** [comment]
We can add that default value to hive-site.xml /cdh manager, but I think is much better if clean the produced JSON for the ext_multimedia field here https://github.com/gbif/occurrence/blob/master/occurrence-hive/src/main/java/org/gbif/occurrence/hive/udf/CollectMediaTypesUDF.java or here https://github.com/gbif/occurrence/blob/master/occurrence-common/src/main/java/org/gbif/occurrence/common/json/MediaSerDeserUtils.java#L81
