### ISSUE TITLE
format of citations in citations.txt

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/occurrence#42]
I noticed that the references to datasets in citations.txt tend to have several mentions of the DOI, e.g.

in 'citations.txt':
> Estrelles E (2017). Colección del Banco de Germoplasma de la Universitat de València. Botanical Garden, University of Valencia. Occurrence Dataset **https://doi.org/10.15470/dktqcx** accessed via GBIF.org on 2018-03-07., **http://doi.org/10.15470/dktqcx** **10.15470/dktqcx**

(DOI mentioned 3 times)

The citation on the dataset page seems more appropriate:
> Estrelles E (2017). Colección del Banco de Germoplasma de la Universitat de València. Botanical Garden, University of Valencia. Occurrence Dataset https://doi.org/10.15470/dktqcx accessed via GBIF.org on 2018-04-16.

This example is from [0016321-180131172636756](https://www.gbif.org/occurrence/download/0016321-180131172636756) ([citations.txt](https://github.com/gbif/occurrence/files/1915424/citations.txt) attached)

Is this intentional?

**Comment by MattBlissett** [comment]
I think it's probably from when the citation format was set by the publisher, to ensure there was a DOI somewhere.
