### ISSUE TITLE
URL mentioned in README 404s

### ISSUE THREAD

**Issue by umeldt** [gbif/occurrence#44]
The README links to http://www.gbif.org/infrastructure/occurrences , which seems to either have been moved or removed.

**Comment by MattBlissett** [comment]
@gbif/comms / @thomasstjerne: I have copied (and reviewed and edited) the content from the old site into the new one. There are now four new articles.

Could you add appropriate links between the items? I'm not sure what the correct way to do that is, in Contentful.

* https://www.gbif.org/infrastructure/summary
* https://www.gbif.org/resource/search?topics=INFRASTRUCTURE

**Comment by dnoesgaard** [comment]
@MattBlissett, I'm not sure what do mean by "appropriate links"?

Also, _topics_ is a controlled ENUM that we usually don't use for anything other than data use summaries. Can you explain what you're trying to achieve?

**Comment by dnoesgaard** [comment]
We don't have a model for such content in Contentful, but perhaps we should...

@thomasstjerne - suggestions welcome :)

**Comment by dnoesgaard** [comment]
To be continued in in https://github.com/gbif/portal-feedback/issues/1352

(please close this one)
