### ISSUE TITLE
add autocomplete for eventId, networkKey, HostKey

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#47]
If we are to add eventId, networkKey etc to the occurrence search, it would make best sense if we had searched it like we do other fields (occurrenceId, publisher, recordedBy etc) - with an autocomplete.

fields that need an autocomplete
installationKey, networkKey, eventId, samplingProtocol

**Comment by MattBlissett** [comment]
I think this was done some time ago.
