### ISSUE TITLE
stateProvince field missing from simple CSV download

### ISSUE THREAD

**Issue by kbraak** [gbif/occurrence#5]
Requirement captured from helpdesk in reporter's words:

> I have a suggestion for your export options. It would be really helpful
> to have the stateProvince field included in the simple export file. This
> data is available in the Darwin core file, and is very useful for
> sorting records by state. It's one of my most frequently used fields,
> and would be nice to have access in the simple.csv output.

**Comment by cgendreau** [comment]
There is also a PullRequest to merge that would add a field to tabular downloads.
https://github.com/gbif/occurrence/pull/2
