### ISSUE TITLE
SOLR search for eventId returns odd results

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#54]
get facets for eventid on a dataset
http://api.gbif-dev.org/v1/occurrence/search?limit=0&datasetKey=40c0f670-ee87-4576-be9d-2725e0b47035&facet=event_id

```
"facets": [
{
"field": "EVENT_ID",
"counts": [
{
"name": "COORONG AND LAKES WATER BIRDS",
"count": 114323
},
{
"name": "SAOA 2ND BIRD ATLAS  ADELAIDE REGION",
"count": 105335
},
...
```

this should mean 105335 results for `eventID = SAOA 2ND BIRD ATLAS  ADELAIDE REGION`

but a search for it returns zero results: 
http://api.gbif-dev.org/v1/occurrence/search?datasetKey=40c0f670-ee87-4576-be9d-2725e0b47035&event_id=SAOA%202ND%20BIRD%20ATLAS%20ADELAIDE%20REGION

same for UAT

**Comment by fmendezh** [comment]
Closing this issues, it seems it  has been fixed now:
lowercase match
http://api.gbif.org/v1/occurrence/search?datasetKey=40c0f670-ee87-4576-be9d-2725e0b47035&event_id=saoa%202nd%20bird%20atlas%20%20adelaide%20region 

uppercase match:
http://api.gbif.org/v1/occurrence/search?datasetKey=40c0f670-ee87-4576-be9d-2725e0b47035&event_id=SAOA%202ND%20BIRD%20ATLAS%20%20ADELAIDE%20REGION
