### ISSUE TITLE
Save query as string in addition to predicate structure

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#6]
It would be practical to have download queries as a readable string in addition to the query params.

```
"request": {
  "predicate": {
    "type": "equals",
    "key": "TAXON_KEY",
    "value": "6164622"
  },
  "format": "SIMPLE_CSV",
  "sendNotification": true
}
```

could be augmented with `"humanReadableRequest": "Taxon: Puma concolor subsp. puma Molina, 1782"` or possible still atomised, but with keys resolved?

Taxon keys change over time and it would be simpler when displaying it.

**Comment by MortenHofft** [comment]
We do not display the human readable string correctly on the current site. This seems like a chance to fix that. OR and AND queries are displayed the same. 

Example:
'or' query http://api.gbif.org/v1/occurrence/download/0057928-160910150852091 
[displayed version](http://www.gbif.org/occurrence/download/0057928-160910150852091)

'and' http://api.gbif.org/v1/occurrence/download/0057929-160910150852091 
[displayed version](http://www.gbif.org/occurrence/download/0057929-160910150852091)

Further complex queries has a link to rerun the query, but of course it doesn't work as the interface cannot display that query.

**Comment by mdoering** [comment]
A few quick remarks: taxon keys do not change over time for a name - or at least they should not and it would be a bug. The reason why the human string is now wrongly displayed is that we only geared the code towards filters that can be generated with the portal. And these are always AND queries at the root, never OR. It is http parameters based, not the full fledged predicate complexity. But I certainly agree it would be good to get that implemented properly.

Not sure if attaching the human query string is really needed as one can always recreate it from the predicate. And the code to generate it needs to exist in both cases anyways.

**Comment by MortenHofft** [comment]
Yeah, I'm starting to have second thoughts as well. Tim also told me the other day, that keys were stable. I had misunderstood that. 

It was really motivated by the misunderstanding that we weren't able to recreate the original query combined with a desire to reuse existing java code for outputting the query. But since we only do so correctly for the simple portal downloads, the gain is somewhat smaller.

**Comment by MortenHofft** [comment]
I've implemented this client side instead
