### ISSUE TITLE
Improve collection of dataset usages and citation on occurrence downloads

### ISSUE THREAD

**Issue by fmendezh** [gbif/occurrence#63]
The occurrence download workflow collects information about datasets usages (# of records used in a download) and citation. Currently, that process is done by collecting a information of a dataset (using a remote [WS call](https://github.com/gbif/occurrence/blob/master/occurrence-download/src/main/java/org/gbif/occurrence/download/citations/CitationsFileReader.java#L123)) and then updating its usage data (by doing, again, a remote [WS call](https://github.com/gbif/occurrence/blob/master/occurrence-download/src/main/java/org/gbif/occurrence/download/citations/CitationsFileReader.java#L130)), such process can be improved by implementing a Bulk API that allows the update of all (or at least batches) of dataset usages.
Some alternatives that worth exploring are:

- Use Postgresql multi insert statements: INSERT INTO table (columns) VALUES row1,row, ...rowN. This would require to change the MyBatis [mapper](https://github.com/gbif/registry/blob/master/registry-ws/src/main/resources/org/gbif/registry/persistence/mapper/DatasetOccurrenceDownloadMapper.xml#L20) by adding a new method that receives a list of dataset usages and performs in a single transaction multiple inserts.
- Use the Postgresql [COPY DATA statement](https://www.postgresql.org/docs/9.2/static/sql-copy.html). By analysing the performance only, this option seems to be the most efficient but it requires the creation of a input file (or InputStream), see [CopyManager](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html).
- Use [CTE](https://www.postgresql.org/docs/9.1/static/queries-with.html) (Common Table Expressions) to create a temporary table with all the usages and then apply all the inserts from the database. This alternatives, in comparison to the previous 2 could facilitate the implementation of SQL statement that joins all the require data to avoid contacting the dataset WS to get the title and citation text.

**Comment by aalbatross** [comment]
Supporting registry-ws with bulkCreate service for updating registry database with multiinserts. Issue opened and linked here
https://github.com/gbif/registry/issues/57
