### ISSUE TITLE
Download species list of an occurrence download

### ISSUE THREAD

**Issue by fmendezh** [gbif/occurrence#65]
A frequent request has been to  allow the download of a species list derived from an ad-hoc occurrence search, this can be provided as an additional download format similar to simple-csv existing format (i.e.: a zip file that only contains 1 file). 
The suggested fields(DwcTerms) and order of those are:
taxonKey, scientificName, count(distinct # of records by taxonKey), rank, taxonomicStatus, kingdom, kingdomKey, phylum, phylumKey,class, classKey,order, orderKey, family, familyKey, genus, genusKey, subgenus, subgenusKey, species, speciesKey.

I'd recommend that initially we should implement this feature in the current mechanism for big-downloads (Hadoop-Hive) only. This will require non-breaking API changes that will affect the following components, project and classes (this is only first pass suggestion):
 -  [DownloadFormat](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/model/occurrence/DownloadFormat.java#L6): Add a new SPECIES_LIST format
- Add the new download format to the RegistryDB schema, use [download-cancelled-status.xml](https://github.com/gbif/registry/blob/master/registry-liquibase/src/main/resources/liquibase/018-download-cancelled-status.xml) as template
- Implement a new [Oozie download](https://github.com/gbif/occurrence/tree/master/occurrence-download/src/main/resources/download-workflow) sub-workflow (species-list) to implement this download, use the simple-csv as example/template, it already uses the compress output format which facilitates the process of creating a zip file.

**Comment by aalbatross** [comment]
Available in prod
Big download example
https://www.gbif.org/occurrence/download/0006329-190307172214381
small download example
https://www.gbif.org/occurrence/download/0006337-190307172214381

download request body sample :
{
"creator":"user",
"notification_addresses": ["user@acad.edu"],
"send_notification":"true",
"format": "SPECIES_LIST",
"predicate":{
"type": "equals",
"key": "TAXON_KEY",
"value": "2431548"
}
}
