### ISSUE TITLE
Implement SQL download API

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#71]
In discussion with users over time, and in particular @peterdesmet we have recognised that data delivered through GBIF is often overly difficult to use for certain purposes.  The formats are restricted and predefined, without flexibility to e.g. choose columns, roll up counts, apply groupings etc at the caller's discretion. The result is that the GBIF systems often generate more information than necessary, and the user needs to post-process all the content. This problem grows as data volumes increase.

Rather than expanding the API with custom parameters to achieve these, we identify that a SQL API would be beneficial and enable a lot of creative use. 

However, the risk of using this API is that when a user applies e.g. `GROUP BY` they lose the ability to inspect the data provenance chain and potentially will overlook the many data quality flags that are available to them. GBIF need to clearly document the implications of using this service and assist users in crafting good queries by providing good examples.

I propose this be a new `format` in the [occurrence/download](https://www.gbif.org/developer/occurrence#download) API allowing e.g.:

```
{
  "creator": "userName",
  "notification_address": [
    "userEmail@example.com"
  ],
  "format": "SQL",
  "sql": "SELECT basisOfRecord, count(DISTINCT speciesKey) AS speciesCount FROM occurrence WHERE year=2018 GROUP BY basisOfRecord"
}
```

The response is to be a single compressed tab-delimited file (CSVs are problematic) with a header row. E.g.
```
basisOfRecord      speciesCount
HumanObservation   1234 
```

Being tab-delimited we need to replace `\t` with a ` ` for all string fields.

Data delivered must continue to conform to the existing license and citation practices (e.g. DOIs and linking the output to the source of the data).

The SQL should support the format of the following only:
```
SELECT ... 
FROM occurrence 
WHERE ... 
GROUP BY ...
``` 

The `occurrence` table will be replaced at runtime with the correct table name, but this will allow for easily readable statements.

This will allow a `SELECT DISTINCT datasetKey, count(*) FROM .... WHERE ....` to determine the attribution chain for the DOI metadata.

Within the `SELECT` we should enable common UDFs such as `avg`, `lower`, `count`, `min`, `max`, `round`, `floor`, `ceil`, `concat`, `year`, `month` etc  (i.e. a subset of the [the Hive UDFs](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF) that make sense). A full list of supported UDFs should be made available in the documentation.

We will not support any joins, inner selects or unions.

All SQL has to be thoroughly sanitized before running to conform to the structure supported to safeguard against bad queries.

An API allowing a user to check the validity of SQL before running is needed. That can be achieved through an `EXPLAIN...` call to Hive and then either confirming it is correct, or propagating the error message explaining the problem.

**Comment by fmendezh** [comment]
The sql download must expose the following endpoints:
 - occurrence/download/request/sql/validate {GET}: this endpoint checks if the provided query is valid and can be accepted
- occurrence/download/request/sql/describe {GET}: provides a list of  [columns,dataType] of the available columns of the Hive table.
- occurrence/download/request/sql {POST}: endpoint to submit sql download, later we can decide if this url is really needed since it can be supported from the existing occurrence/download/request by adding a new type of predicate to the api

SQL Statement:
- Only SELECT statements are accepted and must follow the structure:
    `SELECT (DISTINCT|COUNT col),... 
      FROM occurrence 
      GROUP BY ...
      HAVING ...  
      ORDER BY ...
      LIMIT ...`
   - The `FROM` can be omitted since we always use the same table

**Comment by aalbatross** [comment]
SQL Download API is available in api.gbif-uat.org now for testing around.
Please refer the doc
https://github.com/gbif/occurrence/blob/master/occurrence-download/docs/SQL-Download-API.md

**Comment by abubelinha** [comment]
> SQL Download API is available in api.gbif-uat.org now for testing around.
> Please refer the doc
> https://github.com/gbif/occurrence/blob/master/occurrence-download/docs/SQL-Download-API.md

Is this really available for testing?
I tried the curl example urls but didn't work for me (http error 404)

**Comment by timrobertson100** [comment]
Sorry @abubelinha, this issue should have been closed.

The SQL API never worked out in testing and was backed out having never made it to production. We don't have plans to restart this but do anticipate making it easy to use tools like Google Big Query with monthly exports from GBIF.

**Comment by abubelinha** [comment]
> use tools like Google Big Query with monthly exports from GBIF.

Thanks @timrobertson100 ... are there any links github issues or gbif blog posts related to this subject and its timeline?
I guess gbif will pay Google for this service ... but would querying it be free for end users?
