### ISSUE TITLE
Interpreting multimedia licenses

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#78]
We don't interpret multimedia licenses, which will make filtering on them challenging — relevant to https://github.com/gbif/portal16/issues/505 etc.

1. Is it reasonable to normalize those that are an existing, accepted GBIF dataset license, but otherwise leave the verbatim value as-is?

    Our existing license parser would normalize "CC BY-SA 4.0" etc, and a few additional insignificant variations will catch more of the top 50.

    That will leave the licenses without a version (`cc-by`, `(c) Field Museum of Natural History - CC BY-NC`), licenses with a ≤ 3 version, and any other license statement.

2. A larger task would be to normalize some of these other licenses, e.g. V3 CC.

3. We could also ask some of the larger institutions below, like the Field Museum, if they'd add a version to their license.

4. We could copy the occurrence record license into the multimedia license field, where the record comes from a simple `dwc:associatedMedia` term.

CC @ahahn-gbif, @timrobertson100 for opinion.

Top 50 verbatim multimedia licenses:

Rank | Count | Verbatim multimedia object license
--|--|--
1 | 17705889 | NULL
2 | 7274319 | http://creativecommons.org/licenses/by-nc/4.0/
3 | 7227024 | cc-by
4 | 4412339 | http://creativecommons.org/licenses/by/4.0/
5 | 2779068 | https://creativecommons.org/licenses/by/4.0/
6 | 915679 | http://creativecommons.org/licenses/by/4.0/legalcode
7 | 759961 | https://creativecommons.org/licenses/by-nc-sa/3.0/
8 | 600012 | http://creativecommons.org/publicdomain/zero/1.0/
9 | 537529 | http://creativecommons.org/licenses/by-nc/4.0
10 | 479725 | http://creativecommons.org/licenses/by-nc-sa/3.0/
11 | 479301 | https://creativecommons.org/licenses/by/4.0/legalcode#languages
12 | 419809 | http://creativecommons.org/licenses/by-nc-sa/4.0/
13 | 385863 | http://creativecommons.org/licenses/by-nc/3.0/
14 | 342242 | (c) Field Museum of Natural History - CC BY-NC
15 | 335267 | (c) The Field Museum
16 | 318525 | cc-by-nc-nd
17 | 306187 | http://creativecommons.org/licences/by-nc-sa/3.0/legalcode
18 | 268069 | https://creativecommons.org/share-your-work/public-domain/cc0/
19 | 243232 | http://creativecommons.org/licenses/by-sa/4.0/
20 | 236479 | All Rights Reserved
21 | 216931 | Attribution-ShareAlike (BY-SA) Creative Commons License and GNU Free Documentation License (GFDL)
22 | 213826 | CC BY-SA 4.0
23 | 192061 | http://creativecommons.org/licenses/by-nc-nd/4.0/
24 | 165705 | CC BY-SA 3.0
25 | 160169 | http://creativecommons.org/licenses/by-nc/4.0/legalcode
26 | 160028 | Partial images provided by this server are released under the Creative Commons cc-by-sa 3.0 (generic) licence [http://creativecommons.org/licenses/by-sa/3.0/de/]. Please credit images to BGBM following our citation guidelines [http://ww2.bgbm.org/Herbarium/cite.cfm]. If you would like to use images in a format or resolution which is not provided here, please contact us (d.roepert[at]bgbm.org).
27 | 128046 | CC BY-NC-ND 4.0
28 | 86037 | http://creativecommons.org/licenses/by-nc-nd/3.0/
29 | 65206 | CC BY-NC-SA 4.0
30 | 63881 | https://creativecommons.org/licenses/by-nc/4.0/
31 | 60683 | All rights reserved
32 | 50002 | https://creativecommons.org/licenses/by-nc/3.0/
33 | 48794 | Copyright Borror Lab of Bioacoustics, Ohio State University 2018
34 | 43046 | https://creativecommons.org/licenses/by/3.0/
35 | 42798 | CC BY-NC-SA 3.0
36 | 35632 | Creative Commons Attribution
37 | 30022 | CC-BY-SA 3.0
38 | 29449 | http://creativecommons.org/publicdomain/mark/1.0/
39 | 28234 | [Copyright] Field Museum of Natural History - CC BY-NC
40 | 25002 | CC BY-NC-ND 2.5
41 | 23518 | CC0
42 | 22579 | Images of the Herbarium Hamburgense (HBG) specimens are released under the Creative Commons CC-BY-SA 4.0 License [https://creativecommons.org/licenses/by-sa/4.0/].
43 | 22389 | all rights reserved
44 | 18420 | Landcare Research
45 | 16419 | https://creativecommons.org/publicdomain/zero/1.0/
46 | 15902 | CC BY-NC 4.0
47 | 14949 | https://creativecommons.org/licenses/by-sa/4.0/legalcode
48 | 13349 | CreativeCommons � Attribution Non-Commercial Share-Alike
49 | 12420 | CC BY-NC-SA, no commercial use
50 | 11512 | The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.  You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission.

**Comment by ahahn-gbif** [comment]
In previous license consultations, multimedia content has always been explicitly excluded, so that the concept of "GBIF-accepted" licenses does not really apply here. Normalization should be fine as long as there is no danger of misinterpretation, so particularly with licenses, I would prefer to maintain the verbatim value on the side. I agree that consulting with some of of the larger contributors is a good idea. 

For the purpose of filtering on image use permissions, is the primary goal at the time being to support major exports (e.g. image analysis studies), and only the secondary one to offer facet filters to users? If so, I would start on the safe side, with easily interpreted licenses, and then follow up with publishers of the rest, possibly supported by better ideas of what these images can contribute to.

**Comment by jlegind** [comment]
It was mentioned that it would be useful having an overview of which datasets with image records had dwc:associatedMedia and which used the multimedia extension.
I suspect we have to look into the archives themselves to figure it out, unless the log files can give us a clue? @MattBlissett

**Comment by MattBlissett** [comment]
There's not something already doing this, so

1. Could search with Hive for records where `v_associatedmedia` isn't null, and compare with records having anything in `occurrence_multimedia`.

2. Could do something like
```shell
grep http://rs.gbif.org/terms/1.0/Multimedia storage/dwca/00*/meta.xml
grep http://rs.tdwg.org/dwc/terms/associatedMedia storage/dwca/00*/meta.xml
grep http://rs.tdwg.org/ac/terms/Multimedia storage/dwca/00*/meta.xml
```
on a CLI machine. (remove the `00` to search all, but it will then take a few minutes.) That doesn't mean the extensions have any records, empty extensions are fairly common.

Some datasets use both; we combine them based on the provided media identifier i.e. URL.

**Comment by MattBlissett** [comment]
@ahahn-gbif, [license_uri.tsv](https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/license_uri.tsv) is the initial mapping.

Compared to dataset licensing, it has many more, and some small differences: it doesn't convert  `public domain` or `http://www.opendatacommons.org/licenses/pddl/1.0` into CC0, or `http://www.opendatacommons.org/licenses/by/1.0` into CC_BY_4_0.

Almost all of the recognizable licenses from the top 50 will be parsed successfully. The exceptions are cases like `(c) Field Museum of Natural History - CC BY-NC`. Not in the top 50, but I also haven't added the country-specific V3 licenses, like CC-BY (de).

Like the dataset licenses, an unversioned license (`CC-BY`) is taken to mean the current, 4.0 version of the CC license.

My goal here is to see what we even have, so we can see what could be possible for user searches or image analysis studies.

**Comment by jlegind** [comment]
> There's not something already doing this, so
> 
> 1. Could search with Hive for records where `v_associatedmedia` isn't null, and compare with records having anything in `occurrence_multimedia`.

So that means: If a dataset has v_associatedmedia content but nothing in occurrence_multimedia, then it does not rely on the multimedia extension but on simple multimedia?

**Comment by MattBlissett** [comment]
There will be something in occurrence_multimedia or occurrence_hdfs.ext_multimedia for everything that has any multimedia at all, since the result of interpretation is to tidy everything into a multimedia extension regardless of source.

Simple multimedia only: https://www.gbif.org/occurrence/1934822615

An extension only: https://api.gbif.org/v1/occurrence/1805405971/verbatim

Both ways the same item: https://www.gbif.org/occurrence/1801081741

Maybe:
```sql
select count(*) as c, publishingorgkey, datasetkey, v_associatedmedia is null
from prod_f.occurrence_hdfs
where ext_multimedia is not null
group by publishingorgkey, datasetkey, v_associatedmedia is null order by c desc;
```

**Comment by MattBlissett** [comment]
Multimedia licenses are now interpreted, fairly strictly following https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/license_uri.tsv
