### ISSUE TITLE
Remove temporary data of canceled downloads

### ISSUE THREAD

**Issue by fmendezh** [gbif/occurrence#81]
Occurrence downloads are not handling cancelations gratefull. When a user requests the cancelation of a download job, its particular Oozie workflow is also canceled without taking any precautions on all temporary data structures created: verbatim and interpreted files/tables, citations tables, count tables, etc.

**Specific data removal tasks**
- Remove all temporary folders  and files created by small downloads
- Remove all Hive tables: verbatim, interpreted, citations, counts, species lists, etc.
- Delete all dataset citations from the table `dataset_occurrence_download`
- Remove all the records of canceled downloads in existing tables.
- Do not use a blocking operation to implement this enhancement, i.e., a user must not wait until all data is removed to continue.

**Technical suggestions**
- Always use DROP IF NOT EXISTS as way to avoid undesired errors.
- Create a new method in the registry persistence layer to remove all the records by download ID from  `dataset_occurrence_download`.
- Extend existing Ooozie workflows with an additional parameter to execute a clean-up task, similar to the final actions of existing workflows; i.e.: 
```
DownloadPrepareAction (Existing Java Action) --> IsCleanup? (New Decision Action) 
 YES --> Drop tables (Hive Action) --> Remove all records(Java Action)
 NO  --> Run the existing download workflow
```
- Create a new Oozie workflow that deals with cancelations only.
- Create Oozie coordinator job than periodically deletes all the data of canceled downloads.

**Comment by aalbatross** [comment]
Available as jenkins job, runs weekly
https://builds.gbif.org/job/occurrence-download-cleanup/
