### ISSUE TITLE
Occurrence JSON serialization broken

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#82]
The current occurrence-ws includes absent fields as `null`, and dates as integers since 1970.

This could be related to changes in gbif-common-ws, or gbif-api.

Blocks release.

Dev/UAT https://api.gbif-uat.org/v1/occurrence/1861345850
```
"lastCrawled": 1533759036136,
"lastParsed": 1531351067373,
"crawlId": 185,
"extensions": {},
"basisOfRecord": "PRESERVED_SPECIMEN",
"individualCount": null,
"sex": null,
"lifeStage": null,
"establishmentMeans": null,
```

Prod: https://api.gbif.org/v1/occurrence/1861345850
```
"lastCrawled": "2018-11-28T09:17:35.224+0000",
"lastParsed": "2018-07-11T23:17:47.373+0000",
"crawlId": 201,
"extensions": {},
"basisOfRecord": "PRESERVED_SPECIMEN",
```

**Comment by MattBlissett** [comment]
I had a go with a `git bisect` script to find where this started, but without much success — it's in one of the dependencies, but so many of the branch commits don't build because the snapshot release of the API is no longer the same, it can't narrow it down further.

For interest though: https://git-scm.com/docs/git-bisect

```
git bisect start
git bisect bad
git bisect good occurrence-0.88    # (Version running on prod.)
git bisect run ./test-script
```

`test-script`:
```shell
#!/bin/zsh

mvn -pl .,occurrence-common,occurrence-persistence,occurrence-search,occurrence-ws clean install -DskipTests || exit 125

cd occurrence-ws

mvn -Pdev jetty:run &> $(git rev-parse HEAD).log &

maven=$!

echo "Started Jetty on PID $maven"

until curl -Ss localhost:8080/occurrence/263; do
  sleep 2
done

echo "Revision" $(git rev-parse HEAD)

if curl -Ss localhost:8080/occurrence/263 | jq -S . | tee $(git rev-parse HEAD).json | grep --count basisOfRecord; then
  echo "Works"
else
  echo "Broken"
  kill $maven
  exit 125
fi

if curl -Ss localhost:8080/occurrence/263 | jq -S . | tee $(git rev-parse HEAD).json | grep --count null; then
  echo "Bad"
  kill $maven
  exit 1
else
  echo "Good"
  kill $maven
  exit 0
fi
```

**Comment by fmendezh** [comment]
A recently introduced JacksonContextResolver was causing that behavior, it was removed in this commit:
 https://github.com/gbif/occurrence/commit/3bec300b07d1d6bd4ebde1d85501daea20f267a1

**Comment by MattBlissett** [comment]
We still have

```
"countryCode": null,
```

on such occurrences.
