### ISSUE TITLE
Species download format

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#92]
The current download for species download is confusing for synonyms.

We have for example in [this download](http://api.gbif-uat.org/v1/occurrence/download/request/0000052-190220142031201.zip) the following

taxonKey | scientificName | numberOfOccurrences | rank | taxonomicStatus
--- | --- | --- | --- | --- 
2435079 | Neofelis nebulosa (Griffith, 1821) | 2 | SPECIES | SYNONYM 
2435079 | Neofelis nebulosa (Griffith, 1821) | 170 | SPECIES | ACCEPTED 
2435079 | Neofelis nebulosa (Griffith, 1821) | 5 | SPECIES | HOMOTYPIC_SYNONYM 

Nowhere on the row does it show the non accepted name, or the keys for that.

I suggest changing to explicitly have the fields of `taxonKey`, `scientificName`, `acceptedTaxonKey`, `acceptedScientificName`

**Comment by mdoering** [comment]
Indeed confusing, I agree with the proposal. Checklistbank uses a slightly different terminology for the keys: `key` & `acceptedKey` which I would slightly prefer cause _taxon_ implies it is accepted and does not make much sense for a synonym. The current taxonKey is the accepted(Taxon)Key and the download should provide the synonyms key and name instead

**Comment by MattBlissett** [comment]
Should `taxonRank` then be changed to `rank`?

There is an empty `subgenus` column, do we actually have any subgenera? I don't think so...

`numOfOccurrences` → `numberOfOccurrences` is also sensible; I don't like abbreviations unless they're absolutely necessary.

**Comment by mdoering** [comment]
`subgenus` is indeed never used and can go.
dwc:taxonRank is the Darwin Core term and we use it in Occurrence.taxonRank, but we use just NameUsage.rank for species so I would also rather align that with the NameUsage version as its downloading species not occurrences. Ideally we should harmonize them all at some stage :)

**Comment by aalbatross** [comment]
Ordered species list download as 
taxonKey | scientificName | acceptedTaxonKey | acceptedScientificName | numberOfOccurrences
added acceptedTaxonKey and acceptedScientificName
removed subgenus and subgenuskey
renamed numOfOccurrences -> numberOfOccurrences

small download
https://www.gbif-dev.org/occurrence/download/0000641-181121175518854
large download
https://www.gbif-dev.org/occurrence/download/0000644-181121175518854

**Comment by aalbatross** [comment]
Available in prod
Big download example
https://www.gbif.org/occurrence/download/0006329-190307172214381
small download example
https://www.gbif.org/occurrence/download/0006337-190307172214381
