### ISSUE TITLE
More lenient interpretation of individualCount NULL

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#94]
It is relatively common that numerical values that should be NULL are presented as 0.

A consequence is that GBIF will infer absence when `individualCount` is stated as 0 but not intended. When an explicit statement of presence is given in `occurrenceStatus` we should be more lenient e.g.:

```
If (individualCount == 0 AND occurrenceStatus == ‘present’) then individualCount = NULL
```

This would be implemented somewhere around [here](https://github.com/gbif/occurrence/blob/master/occurrence-processor/src/main/java/org/gbif/occurrence/processor/interpreting/OccurrenceInterpreter.java#L200)

**Comment by timrobertson100** [comment]
@MattBlissett can you please provide your opinion or implement if you agree?

**Comment by tucotuco** [comment]
I agree with this interpretation. Whether you put it in practice or no, I
think we should also document the best practice in the term commentaries
(see ). What do you think about documenting what GBIF does in the Darwin
Core Q&A? Is that too much a moving target to keep up with? If so, could we
point to documentation done by GBIF within DwC Q&A?

**Comment by MattBlissett** [comment]
This affects about 20,000,000 records.

We don't yet interpret `occurrenceStatus`. That can wait for pipelines, so I will handle the existing cases: `present`, `Present` and `Presente` and `individualCount` being `0`.

What did you mean by "GBIF will infer absence"?

John: I think we will work on improving the documentation around GBIF interpretation later this year, at the moment too many questions require me to read the source code to see what we do.
