### ISSUE TITLE
Occurrence ID from Int to Long

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#97]
The GBIF occurrence ID is currently an Int and needs to be a long. This will involve

- [x] gbif-api change for model (core and extensions)
- [x] review / changes of the occurrence lookup code
- [x] review / changes of the occurrence Solr schema, CRUD code and morphlines
- [x] review / changes of the occurrence small download
- [x] review / changes of the occurrence large download (i.e. hive)
- [x] review / changes of the analytics Hive scripts
- [x] review / changes of the metrics/cube (unlikely to be issue)
- [x] review / changes of the maps (unlikely to be issue)

**Comment by fmendezh** [comment]
Fixes for Solr schema and HDFS table: https://github.com/gbif/occurrence/commit/41a3b771360c6add494f78f02b5e262dd74c0f60

**Comment by MattBlissett** [comment]
Tasks:
- [ ] Update API for maps (SOLR queries will need it)
- [ ] Release occurrence and dependent libraries
- [ ] Release maps
- [ ] Release metrics
- [ ] Verify prod_g_occurrence and prod_g_occurrence_lookup look OK.
- [ ] Update prod CLI configs to prod_g
- [ ] Recrawl eBird (and the rest of the crawl queue? We don't really have a way not to.)
- [ ] Recrawl the other part-crawled datasets: 4bfac3ea-8763-4f4b-a71a-76a6f5f243d3 6728c42d-c4b6-4fda-a211-5ad1bb59cda4 e4deab67-0998-4140-b573-0ba1f624eb3e 6ce9819a-d82b-41e1-9059-0dd201f15993 e87a12af-fc4c-4315-bff7-c7b827379aca
- [ ] Build HDFS prod_g
- [ ] Build SOLR index from prod_g
- [ ] (Build maps, cubes)
- [ ] Test APIs
- [ ] Update WS config to prod_g
- [ ] Update download workflow to work from prod_g
