### ISSUE TITLE
list user occurrence downloads route: no useful messages given on error

### ISSUE THREAD

**Issue by sckott** [gbif/occurrence#98]
I know at this time I have 394 downloads listed in my account on GBIF. I can get the first 300 no problem

curl -v -H 'Authorization: Basic <simple auth string>' -H 'Content-Type: application/json' -H 'Accept: application/json' 'https://api.gbif.org/v1/occurrence/download/user/sckott?limit=300'

But if I try to use offset I start to run into problems because there are no useful indicators of what's gone wrong.

e.g.,  this works fine:

curl -v -H 'Authorization: Basic <simple auth string>' -H 'Content-Type: application/json' -H 'Accept: application/json' 'https://api.gbif.org/v1/occurrence/download/user/sckott?limit=4&offset=300'

but this fails with 500, but no useful response headers, and no response body:

curl -v -H 'Authorization: Basic <simple auth string>' -H 'Content-Type: application/json' -H 'Accept: application/json' 'https://api.gbif.org/v1/occurrence/download/user/sckott?limit=40&offset=300'

- I know I should have more than 340 downloads in my account. Maybe there arent actually that many? But it shouldn't error if that's the case.
- Maybe there is some hard cap in number of items this route will return that I don't know about?
- If possible could a different 500 series code be given, and a JSON response body be returned with a useful error message? or even a response header with something useful if no body?

**Comment by sckott** [comment]
any thoughts on this?

**Comment by timrobertson100** [comment]
I'm really sorry this went unanswered @sckott 

I've just tried a few requests and can't reproduce this with my credentials.

```
-- page 1
curl --user trobertson:removed 'https://api.gbif.org/v1/occurrence/download/user/sckott?limit=10&offset=400'

-- page 2
curl --user trobertson:removed 'https://api.gbif.org/v1/occurrence/download/user/sckott?limit=10&offset=410'

-- page 3, no records 
curl --user trobertson:removed 'https://api.gbif.org/v1/occurrence/download/user/sckott?limit=10&offset=420'
```

Can you please confirm that format of request definitely does not return for your account? If not, I'll dig in further.

**Comment by sckott** [comment]
thanks @timrobertson100 

hadn't tried this again since I opened this, just checked again now and it now works. Possible that it was a temporary problem that is now fixed?

**Comment by timrobertson100** [comment]
Most likely we were having a short outage of some sort given it was a 500 you saw.

Please don't be shy about prompting me on email if questions go unanswered for too long. There can sometimes be a lot of traffic on various channels and things can go unanswered unintentionally...

**Comment by sckott** [comment]
ok, thanks!
